export default {
  TOI_THEO_DAY_CAM_KET_VA_DONG_Y_RANG_BAT_KY_SU_GIAN_DOI_NAO_TRONG_VIEC_CAM_KET_XEM_XET_XAC_NHAN_CAC_HO_SO_CUA_KHACH_HANG_HOAC_HO_SO_HINH_ANH_DO_TOI_TU_CHUP_CUNG_DEU_LA_HANH_VI_VI_PHAM_NGHIEM_TRONG_NOI_QUY_CUA_CONG_TY_VA_SE_PHAI_CHIU_KY_LUAT_MUC_CAO_NHAT_LA_SA_THAI_VA_PHAI_BOI_THUONG_MOI_THIET_HAI_CHO_CONG_TY_: "Tôi theo đây cam kết và đồng ý rằng bất kỳ sự gian dối nào trong việc cam kết/xem xét, xác nhận các hồ sơ của khách hàng hoặc hồ sơ, hình ảnh do tôi tự chụp cũng đều là hành vi vi phạm nghiêm trọng nội quy của công ty và sẽ phải chịu kỷ luật mức cao nhất là sa thải và phải bồi thường mọi thiệt hại cho Công ty.",
  NHAN_VIEN_TU_VAN_XAC_NHAN_DA_KIEM_TRA_VA_CHIU_TRACH_NHIEM_VE_TINH_CHINH_XAC_CUA_CAC_THONG_TIN_KHACH_HANG_CUNG_CAP_DONG_THOI_TUAN_THU_NOI_DUNG_VE_CAC_HANH_VI_BI_CAM_VA_CAC_LUU_Y_BAT_BUOC_TUAN_THU_KHI_THUC_HIEN_CONG_VIEC_CUA_JIVF: "Nhân viên Tư vấn xác nhận đã kiểm tra và chịu trách nhiệm về tính chính xác của các thông tin Khách hàng cung cấp; đồng thời tuân thủ nội dung về “Các hành vi bị cấm và các lưu ý bắt buộc tuân thủ khi thực hiện công việc” của JIVF.",
  TAT_CA_NHUNG_HINH_ANH_THONG_TIN_LA_DO_TOI_TU_CHUP_TU_THU_THAP_KHONG_BI_CHINH_SUA_LAM_GIA_HOAC_CO_TINH_LAM_SAI_LECH_CUNG_KHONG_BI_TAC_DONG_TU_KHACH_HANG_HAY_CUA_HANG_LIEN_KET_DE_BO_QUA_BAT_KY_BUOC_KIEM_TRA_HOAC_NGHI_VAN_NAO_: "2. Tất cả những hình ảnh, thông tin là do tôi tự chụp, tự thu thập, không bị chỉnh sửa, làm giả hoặc cố tình làm sai lệch, cũng không bị tác động từ khách hàng hay cửa hàng liên kết để bỏ qua bất kỳ bước kiểm tra hoặc nghi vấn nào.",
  TAT_CA_NHUNG_THONG_TIN_KIEM_TRA_HIEN_TRUONG_XAC_DINH_NHAN_THAN_NOI_O_CUA_KHACH_HANG_DUOC_CUNG_CAP_TRONG_BAO_CAO_KIEM_TRA_HIEN_TRUONG_LA_CHINH_XAC_DUNG_THUC_TE_VA_DO_CHINH_TOI_THUC_HIEN_THEO_QUY_DINH_QUY_TRINH_CUA_CONG_TY_: "1. Tất cả những thông tin kiểm tra hiện trường, xác định nhân thân, nơi ở của khách hàng được cung cấp trong báo cáo kiểm tra hiện trường là chính xác, đúng thực tế và do chính tôi thực hiện theo quy định, quy trình của Công ty.",
  TONG_KHOAN_VAY_DE_XUAT_VA_DU_NO_TIN_CHAP_HIEN_TAI_CUA_KHACH_HANG_KHONG_DUOC_VUOT_QUA_CHECKTOTALLOAN_VND_VUI_LONG_DIEU_CHINH_SO_TIEN_TRA_TRUOC_HOAC_HUONG_DAN_KHACH_HANG_THANH_TOAN_KHOAN_VAY_CU: "Tổng khoản vay đề xuất và Dư nợ tín chấp hiện tại của khách hàng không được vượt quá {{checkTotalLoan}} VND. Vui lòng điều chỉnh Số tiền trả trước hoặc hướng dẫn khách hàng thanh toán khoản vay cũ",
  HIEN_TAI_QUY_KHACH_CHUA_DU_DIEU_KIEN_VAY_TAI_JIVF_CAM_ON_QUY_KHACH_DA_QUAN_TAM_DEN_DICH_VU_CUA_CHUNG_TOI: "Hiện tại Quý khách chưa đủ điều kiện vay tại JIVF. Cảm ơn Quý khách đã quan tâm đến dịch vụ của chúng tôi",
  DA_HET_GIO_LAM_VIEC_VUI_LONG_THUC_HIEN_THAO_TAC_TRONG_KHOANG_THOI_GIAN_TU_STARTTIME_DEN_ENDTIME: "Đã hết giờ làm việc, vui lòng thực hiện thao tác trong khoảng thời gian từ {{startTime}} đến {{endTime}}",
  DIA_CHI_THUONG_TRU_KHONG_DAY_DU_DU_LIEU_VUI_LONG_NHAP_THONG_TIN_DIA_CHI_HIEN_TAI: "Địa chỉ thường trú không đầy đủ dữ liệu. Vui lòng nhập thông tin địa chỉ hiện tại",
  FILE_TAI_LEN_CO_DINH_DANG_PDF_HOAC_HINH_ANH_JPG_JPEG_PNG_VA_KHONG_VUOT_QUA_5MB: "File tải lên có định dạng .pdf hoặc hình ảnh .jpg, .jpeg, .png và không vượt quá 5MB",
  VUI_LONG_NHAP_DUNG_SO_CMND_HOAC_LIEN_HE_BO_PHAN_KINH_DOANH_DE_DUOC_HUONG_DAN: "Vui lòng nhập đúng số CMND hoặc liên hệ bộ phận kinh doanh để được hướng dẫn",
  TY_LE_TRA_TRUOC_TOI_THIEU_CHO_CHUONG_TRINH_VAY_LA_MINIMUMPREPAYMENTPERCENT: "Tỷ lệ trả trước tối thiểu cho chương trình vay là {{minimumPrepaymentPercent}} %",
  PCB_CIC_KHONG_CO_PHAN_HOI_VUI_LONG_GUI_LAI_HO_SO_DE_TRA_CUU_LAI_HOAC_THOAT: "PCB/CIC không có phản hồi, vui lòng gửi lại hồ sơ để tra cứu lại hoặc thoát",
  SO_DIEN_THOAI_KHACH_HANG_KHONG_DUOC_TRUNG_VOI_SO_DIEN_THOAI_NGUOI_LIEN_HE: "Số điện thoại khách hàng không được trùng với số điện thoại người liên hệ",
  TY_LE_TRA_TRUOC_TOI_DA_CHO_CHUONG_TRINH_VAY_LA_MAXIMUMPREPAYMENTPERCENT: "Tỷ lệ trả trước tối đa cho chương trình vay là {{maximumPrepaymentPercent}} %",
  SO_TIEN_VAY_GOC_TOI_THIEU_CUA_CHUONG_TRINH_VAY_LA_MINIMUMLOANAMOUNT_VND: "Số tiền vay gốc tối thiểu của chương trình vay là: {{minimumLoanAmount}} VND",
  SO_TIEN_VAY_GOC_TOI_DA_CUA_CHUONG_TRINH_VAY_LA_MAXIMUMLOANAMOUNT_VND: "Số tiền vay gốc tối đa của chương trình vay là: {{maximumLoanAmount}} VND",
  DIEM_DTI_KHONG_DAT_VUI_LONG_DIEU_CHINH_KHOAN_VAY_HOAC_KY_HAN_PHU_HOP: "Điểm DTI không đạt. Vui lòng điều chỉnh khoản vay hoặc kỳ hạn phù hợp",
  DO_TUOI_KHACH_HANG_KHONG_DAT_DO_TUOI_TOI_THIEU_CUA_CHUONG_TRINH_VAY: "Độ tuổi khách hàng không đạt độ tuổi tối thiểu của chương trình vay",
  NGUOI_LIEN_HE_TRONG_TRUONG_HOP_CAN_THUC_HIEN_NGHIA_VU_THEO_HOP_DONG: "Người liên hệ trong trường hợp cần thực hiện nghĩa vụ theo hợp đồng",
  TONG_SO_TIEN_VAY_VA_DU_NO_HIEN_TAI_CUA_KHACH_HANG_KHONG_VUOT_QUA: "Tổng số tiền vay và dư nợ hiện tại của khách hàng không vượt quá {{totalLoan}} VND",
  FILE_UPLOAD_CO_DINH_DANG_JPG_JPEG_PNG_PDF_VA_KHONG_VUOT_QUA_5MB: "File upload có định dạng .jpg, .jpeg, .png, .pdf và không vượt quá 5MB",
  NGUOI_LIEN_HE_TRONG_TRUONG_HOP_THUC_HIEN_NGHIA_VU_THEO_HOP_DONG: "Người liên hệ trong trường hợp thực hiện nghĩa vụ theo hợp đồng",
  DO_TUOI_KHACH_HANG_VUOT_QUA_DO_TUOI_TOI_DA_CUA_CHUONG_TRINH_VAY: "Độ tuổi khách hàng vượt quá độ tuổi tối đa của chương trình vay",
  SO_DIEN_THOAI_CUA_2_NGUOI_LIEN_HE_KHONG_DUOC_GIONG_NHAU: "Số điện thoại của 2 người liên hệ không được giống nhau",
  NGAY_KY_HOP_DONG_PHAI_LON_HON_HOAC_BANG_NGAY_HIEN_TAI: "Ngày ký hợp đồng phải lớn hơn hoặc bằng ngày hiện tại",
  DIA_CHI_SITE_VISIT_YEU_CAU_GHI_RO_SO_NHA_TEN_DUONG_: "Địa chỉ site visit ( Yêu cầu ghi rõ: số nhà, tên đường)",
  NGAY_CAP_KHONG_DUOC_NHO_HON_NGAY_HET_HAN_CUA_CCCD: "Ngày cấp không được nhỏ hơn ngày hết hạn của CCCD",
  VUI_LONG_NHAP_TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Vui lòng nhập tổng thanh toán nợ vay hàng tháng",
  BAO_HIEM_DUA_TREN_KHA_NANG_TAI_CHINH_KHACH_HANG: "Bảo hiểm dựa trên khả năng tài chính khách hàng",
  BAO_CAO_SITE_VISIT_DANH_CHO_THAM_DINH_HO_SO_VAY: "Báo cáo site visit dành cho thẩm định hồ sơ vay",
  DIA_CHI_THUONG_TRU_GIONG_VOI_NOI_O_HIEN_TAI: "Địa chỉ thường trú giống với nơi ở hiện tại",
  VUI_LONG_NHAP_DAY_DU_CAC_THONG_TIN_BAT_BUOC: "Vui lòng nhập đầy đủ các thông tin bắt buộc",
  CAC_THONG_TIN_DA_NHAP_SE_KHONG_DUOC_LUU_LAI: "Các thông tin đã nhập sẽ không được lưu lại",
  VUI_LONG_NHAP_CHI_PHI_SINH_HOAT_HANG_THANG: "Vui lòng nhập chi phí sinh hoạt hàng tháng",
  THONG_TIN_THU_THAP_TOAN_BO_NOI_DUNG_MUC_B_: "Thông tin thu thập ( toàn bộ nội dung mục B)",
  SO_TIEN_THANH_TOAN_HANG_THANG_GIAI_DOAN_1: "Số tiền thanh toán hàng tháng giai đoạn 1",
  SO_TIEN_THANH_TOAN_HANG_THANG_GIAI_DOAN_2: "Số tiền thanh toán hàng tháng giai đoạn 2",
  NGAY_CAP_KHONG_DUOC_LON_HON_NGAY_HIEN_TAI: "Ngày cấp không được lớn hơn ngày hiện tại",
  NGUOI_LIEN_HE_TRONG_TRUONG_HOP_KHAN_CAP: "Người liên hệ trong trường hợp khẩn cấp",
  NGAY_HET_HAN_PHAI_LON_HON_NGAY_HIEN_TAI: "Ngày hết hạn phải lớn hơn ngày hiện tại",
  VUI_LONG_DIEN_DAY_DU_THONG_TIN_BAT_BUOC: "Vui lòng điền đầy đủ thông tin bắt buộc",
  VUI_LONG_NHAP_TEN_CONG_TY_NOI_LAM_VIEC: "Vui lòng nhập tên công ty/Nơi làm việc",
  NHAP_TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Nhập tổng thanh toán nợ vay hàng tháng",
  VUI_LONG_CHON_NGAY_KY_HOP_DONG_DU_KIEN: "Vui lòng chọn ngày ký hợp đồng dự kiến",
  NGAY_SINH_KHONG_DUOC_LON_HON_NGAY_CAP: "Ngày sinh không được lớn hơn ngày cấp",
  VUI_LONG_NHAP_DUNG_DINH_DANG_CUA_CMND: "Vui lòng nhập đúng định dạng của CMND",
  DIA_CHI_THUONG_TRU_TRUNG_VOI_DIA_CHI: "Địa chỉ thường trú trùng với địa chỉ",
  VUI_LONG_NHAP_SO_DIEN_THOAI_CONG_TY: "Vui lòng nhập số điện thoại công ty",
  _DOC_DOCX_XLS_XLSX_JPG_JPEG_PNG_PDF: ".doc, .docx,.xls, .xlsx, .jpg, .jpeg, .png, .pdf.",
  GIOI_TINH_KHONG_TRUNG_KHOP_VOI_CCCD: "Giới tính không trùng khớp với CCCD",
  VUI_LONG_NHAP_DIA_CHI_NOI_LAM_VIEC: "Vui lòng nhập địa chỉ nơi làm việc",
  CHON_NGHE_NGHIEP_CUA_THU_NHAP_KHAC: "Chọn nghề nghiệp của thu nhập khác",
  KHOAN_THANH_TOAN_NO_VAY_HANG_THANG: "Khoản thanh toán nợ vay hàng tháng",
  NAM_SINH_KHONG_TRUNG_KHOP_VOI_CCCD: "Năm sinh không trùng khớp với CCCD",
  VUI_LONG_CHON_HINH_THUC_THANH_TOAN: "Vui lòng chọn hình thức thanh toán",
  VUI_LONG_NHAP_THU_NHAP_HANG_THANG: "Vui lòng nhập thu nhập hàng tháng",
  TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Tổng thanh toán nợ vay hàng tháng",
  NHAP_CHI_PHI_SINH_HOAT_HANG_THANG: "Nhập chi phí sinh hoạt hàng tháng",
  VUI_LONG_NHAP_DIA_CHI_THUONG_TRU: "Vui lòng nhập địa chỉ thường trú",
  VUI_LONG_NHAP_SO_NGUOI_PHU_THUOC: "Vui lòng nhập số người phụ thuộc",
  LOI_VUI_LONG_THU_LAI_SAU_IT_PHUT: "Lỗi, vui lòng thử lại sau ít phút",
  VUI_LONG_THEM_BAO_CAO_SITE_VISIT: "Vui lòng thêm báo cáo site visit",
  HEM_BAO_CAO_SITE_VISIT_THAT_BAI_: "hêm báo cáo site visit thất bại!",
  VUI_LONG_NHAP_CHI_PHI_SINH_HOAT: "Vui lòng nhập chi phí sinh hoạt",
  VUI_LONG_NHAP_SO_TIEN_TRA_TRUOC: "Vui lòng nhập số tiền trả trước",
  KHACH_HANG_THUC_HIEN_THANH_TOAN: "Khách hàng thực hiện thanh toán",
  VUI_LONG_CHON_TINH_TRANG_CU_TRU: "Vui lòng chọn tình trạng cư trú",
  TEP_TAI_LEN_CHUA_DUNG_DINH_DANG: "Tệp tải lên chưa đúng định dạng",
  DUNG_LUONG_TOI_DA_CHO_PHEP_5MB: "Dung lượng tối đa cho phép 5MB",
  GIA_BAN_TOI_DA_LA_MAXPRICE_VND: "Giá bán tối đa là {{maxPrice}} VND",
  VUI_LONG_CHON_TRINH_DO_HOC_VAN: "Vui lòng chọn trình độ học vấn",
  SO_TIEN_BAO_HIEM_TAM_TINH_VND_: "Số tiền bảo hiểm tạm tính (VND)",
  NHAP_TEN_CONG_TY_NOI_LAM_VIEC: "Nhập tên công ty/Nơi làm việc",
  NGHE_NGHIEP_CUA_THU_NHAP_KHAC: "Nghề nghiệp của thu nhập khác",
  VUI_LONG_NHAP_TY_LE_TRA_TRUOC: "Vui lòng nhập tỷ lệ trả trước",
  VUI_LONG_CHON_NGAY_THANH_TOAN: "Vui lòng chọn ngày thanh toán",
  TONG_SO_TIEN_VAY_MUA_BAO_HIEM: "Tổng số tiền vay mua bảo hiểm",
  TY_LE_PHI_BAO_HIEM_THEO_THANG: "Tỷ lệ phí bảo hiểm theo tháng",
  SO_TIEN_BAO_HIEM_TAM_TINH_VND: "Số tiền bảo hiểm tạm tính (VND)",
  VUI_LONG_NHAP_DIA_CHI_TAM_TRU: "Vui lòng nhập địa chỉ tạm trú",
  VUI_LONG_NHAP_NOI_O_HIEN_TAI: "Vui lòng nhập nơi ở hiện tại",
  CHUONG_TRINH_VAY_VA_SAN_PHAM: "Chương trình vay và sản phẩm",
  THONG_TIN_KHACH_HANG_BO_SUNG: "Thông tin khách hàng bổ sung",
  VUI_LONG_CHON_TINH_THANH_PHO: "Vui lòng chọn tỉnh/ thành phố",
  VUI_LONG_NHAP_THANG_LAM_VIEC: "Vui lòng nhập tháng làm việc",
  CHI_PHI_SINH_HOAT_HANG_THANG: "Chi phí sinh hoạt hàng tháng",
  THONG_TIN_DINH_DANH_CA_NHAN: "Thông tin định danh cá nhân",
  VUI_LONG_NHAP_THU_NHAP_KHAC: "Vui lòng nhập thu nhập khác",
  VUI_LONG_NHAP_SO_DIEN_THOAI: "Vui lòng nhập số điện thoại",
  VUI_LONG_CHON_LY_DO_TU_CHOI: "Vui lòng chọn lý do từ chối",
  VUI_LONG_CHON_LOAI_CHUNG_TU: "Vui lòng chọn loại chứng từ",
  VUI_LONG_NHAP_THANG_CU_TRU: "Vui lòng nhập tháng cư trú",
  NHAP_SO_DIEN_THOAI_CONG_TY: "Nhập số điện thoại công ty",
  NHAP_SO_DIEN_THOAI_DI_DONG: "Nhập số điện thoại di động",
  THONG_TIN_HOP_DONG_MUA_BAN: "Thông tin hợp đồng mua bán",
  NGAY_THANH_TOAN_HANG_THANG: "Ngày thanh toán hàng tháng",
  VUI_LONG_CHON_MUC_DICH_VAY: "Vui lòng chọn mục đích vay",
  VUI_LONG_NHAP_NAM_LAM_VIEC: "Vui lòng nhập năm làm việc",
  VUI_LONG_CHON_NHA_CUNG_CAP: "Vui lòng chọn nhà cung cấp",
  PHI_BAO_HIEM_TAM_TINH_VND_: "Phí bảo hiểm tạm tính (VND)",
  NHAP_DIA_CHI_NOI_LAM_VIEC: "Nhập địa chỉ nơi làm việc",
  NHAP_SO_HOP_DONG_UY_QUYEN: "Nhập Số hợp đồng ủy quyền",
  VUI_LONG_CHON_NGHE_NGHIEP: "Vui lòng chọn nghề nghiệp",
  VUI_LONG_NHAP_TEN_CONG_TY: "Vui lòng nhập tên công ty",
  THONG_TIN_NGUOI_LIEN_QUAN: "Thông tin người liên quan",
  VUI_LONG_CHON_MOI_QUAN_HE: "Vui lòng chọn mối quan hệ",
  THOI_GIAN_LAM_VIEC_DA_HET: "Thời gian làm việc đã hết",
  THONG_TIN_EKYC_KHACH_HANG: "Thông tin eKYC khách hàng",
  CHON_HINH_THUC_THANH_TOAN: "Chọn hình thức thanh toán",
  PHI_BAO_HIEM_TAM_TINH_VND: "Phí bảo hiểm tạm tính (VND)",
  VUI_LONG_NHAP_NAM_CU_TRU: "Vui lòng nhập năm cư trú",
  TEN_CONG_TY_NOI_LAM_VIEC: "Tên công ty/Nơi làm việc",
  NHAP_THU_NHAP_HANG_THANG: "Nhập thu nhập hàng tháng",
  NHAP_SO_HOP_DONG_MUA_BAN: "Nhập Số hợp đồng mua bán",
  NGAY_KI_HOP_DONG_MUA_BAN: "Ngày kí hợp đồng mua bán",
  NGAY_KY_HOP_DONG_DU_KIEN: "Ngày ký hợp đồng dự kiến",
  VUI_LONG_CHON_KY_HAN_VAY: "Vui lòng chọn kỳ hạn vay",
  VUI_LONG_CHON_QUAN_HUYEN: "Vui lòng chọn quận/ huyện",
  THONG_TIN_NGUOI_HON_PHOI: "Thông tin người hôn phối",
  DIA_CHI_THUONG_TRU_EKYC: 'Địa chỉ thường trú ({{ekycType}})',
  NHAP_DIA_CHI_THUONG_TRU: "Nhập địa chỉ thường trú",
  DINH_DANG_FILE_CHO_PHEP: "Định dạng file cho phép",
  THEM_BAO_HIEM_TU_NGUYEN: "Thêm bảo hiểm tự nguyện",
  VUI_LONG_CHON_PHUONG_XA: "Vui lòng chọn phường / xã",
  NHAP_SO_NGUOI_PHU_THUOC: "Nhập số người phụ thuộc",
  VUI_LONG_NHAP_HO_VA_TEN: "Vui lòng nhập họ và tên",
  TONG_GIA_HANG_HOA_TITLE: "Tổng giá {{title}}",
  NHAP_THONG_TIN_THU_THAP: "Nhập thông tin thu thập",
  CHON_TINH_TRANG_CU_TRU: "Chọn tình trạng cư trú",
  NHAP_CHI_PHI_SINH_HOAT: "Nhập chi phí sinh hoạt",
  NHAP_TEN_TEN_GOI_O_NHA: "Nhập tên tên gọi ở nhà",
  VUI_LONG_NHAP_SO_THANG: "Vui lòng nhập số tháng",
  HAY_CHON_LOAI_CHUNG_TU: "Hãy chọn loại chứng từ",
  NHAP_DIA_CHI_SITE_VIST: "Nhập địa chỉ site vist",
  SO_DIEN_THOAI_CONG_TY: "Số điện thoại công ty",
  VUI_LONG_TAI_LEN_FILE: "Vui lòng tải lên file",
  VUI_LONG_KIEM_TRA_LAI: "Vui lòng kiểm tra lại",
  SO_DIEN_THOAI_DI_DONG: "Số điện thoại di động",
  CHON_CHUONG_TRINH_VAY: "Chọn chương trình vay",
  CHON_TRINH_DO_HOC_VAN: "Chọn trình độ học vấn",
  VUI_LONG_CHON_CHUC_VU: "Vui lòng chọn chức vụ",
  VUI_LONG_NHAP_SO_TIEN: "Vui lòng nhập số tiền",
  THEM_CHUNG_TU_BO_SUNG: "Thêm chứng từ bổ sung",
  CHON_TEN_GOI_BAO_HIEM: "Chọn tên gói bảo hiểm",
  VUI_LONG_CHON_CAM_KET: "Vui lòng chọn cam kết",
  VUI_LONG_NHAP_DU_LIEU: "Vui lòng nhập dữ liệu",
  DIA_CHI_NOI_LAM_VIEC: "Địa chỉ nơi làm việc",
  VUI_LONG_CHON_DAI_LY: "Vui lòng chọn đại lý",
  SO_HOP_DONG_UY_QUYEN: "Số hợp đồng ủy quyền",
  CHON_NGAY_THANH_TOAN: "Chọn ngày thanh toán",
  LAI_SUAT_GIAI_DOAN_1: "Lãi suất giai đoạn 1",
  LAI_SUAT_GIAI_DOAN_2: "Lãi suất giai đoạn 2",
  TEN_THUONG_GOI_O_NHA: "Tên thường gọi ở nhà",
  VUI_LONG_NHAP_SO_NAM: "Vui lòng nhập số năm",
  CONG_VIEC_KHACH_HANG: "Công việc khách hàng",
  TAI_CHINH_KHACH_HANG: "Tài chính khách hàng",
  VUI_LONG_UPLOAD_FILE: "Vui lòng upload file",
  GIA_DINH_KET_QUA_DTI: "Giả định kết quả DTI",
  HINH_THUC_THANH_TOAN: "Hình thức thanh toán",
  NHAP_DIA_CHI_TAM_TRU: "Nhập địa chỉ tạm trú",
  GUI_HO_SO_THANH_CONG: "Gửi hồ sơ thành công",
  LUU_HO_SO_THANH_CONG: "Lưu hồ sơ thành công",
  NHAP_NOI_O_HIEN_TAI: "Nhập nơi ở hiện tại",
  THU_NHAP_HANG_THANG: "Thu nhập hàng tháng",
  NGUON_THU_NHAP_KHAC: "Nguồn thu nhập khác",
  NHAP_TEN_NOI_BAN_XE: "Nhập tên nơi bán xe",
  SO_HOP_DONG_MUA_BAN: "Số hợp đồng mua bán",
  THONG_TIN_KHOAN_VAY: "Thông tin khoản vay",
  CHON_TINH_THANH_PHO: "Chọn tỉnh/ thành phố",
  TEP_TAI_LEN_QUA_LON: "Tệp tải lên quá lớn",
  SO_CMND_DA_DUOC_CAP: "Số CMND đã được cấp",
  CHUNG_TU_SITE_VISIT: "Chứng từ site visit",
  DIA_CHI_THUONG_TRU: 'Địa chỉ thường trú',
  NHAP_THU_NHAP_KHAC: "Nhập thu nhập khác",
  THONG_TIN_HANG_HOA: "Thông tin hàng hóa",
  KY_HAN_GIAI_DOAN_1: "Kỳ hạn giai đoạn 1",
  KY_HAN_GIAI_DOAN_2: "Kỳ hạn giai đoạn 2",
  THOI_GIAN_LAM_VIEC: "Thời gian làm việc",
  SO_NGUOI_PHU_THUOC: "Số người phụ thuộc",
  NHAP_SO_DIEN_THOAI: "Nhập số điện thoại",
  BAO_HIEM_TU_NGUYEN: "Bảo hiểm tự nguyện",
  CHON_LY_DO_TU_CHOI: "Chọn lý do từ chối",
  CHON_LOAI_CHUNG_TU: "Chọn loại chứng từ",
  XAC_NHAN_GUI_HO_SO: "Xác nhận gửi hồ sơ",
  BAO_CAO_SITE_VISIT: "Báo cáo site visit",
  DIA_CHI_SITE_VISIT: "địa chỉ site visit",
  THONG_TIN_THU_THAP: "thông tin thu thập",
  TINH_TRANG_CU_TRU: "Tình trạng cư trú",
  CHI_PHI_SINH_HOAT: "Chi phí sinh hoạt",
  CHON_NGAY_HET_HAN: "Chọn ngày hết hạn",
  CHON_NOI_CAP_CCCD: "Chọn nơi cấp CCCD",
  NHOM_SAN_PHAM_VAY: "Nhóm sản phẩm vay",
  NHAP_GIA_CHUA_VAT: "Nhập giá chưa VAT",
  NHAP_SO_TAI_KHOAN: "Nhập số tài khoản",
  CHON_NHA_SAN_XUAT: "Chọn nhà sản xuất",
  CHON_TEN_HANG_HOA: "Chọn Tên hàng hoá",
  TONG_GIA_HANG_HOA: "Tổng giá hàng hóa",
  DON_GIA_CUA_TITLE: "Đơn giá (của {{title}})",
  SO_TIEN_TRA_TRUOC: "Số tiền trả trước",
  CHON_MUC_DICH_VAY: "Chọn mục đích vay",
  CHON_CHON_CHUC_VU: "Chọn chọn chức vụ",
  DE_XUAT_KHOAN_VAY: "Đề xuất khoản vay",
  CHUNG_TU_DINH_KEM: "Chứng từ đính kèm",
  DIEM_DTI_HIEN_TAI: "Điểm DTI hiện tại",
  CHON_NHA_CUNG_CAP: "Chọn nhà cung cấp",
  HUY_BO_SUNG_HO_SO: "Hủy bổ sung hồ sơ",
  THOI_GIAN_CU_TRU: "Thời gian cư trú",
  CHON_NGHE_NGHIEP: "Chọn nghề nghiệp",
  THOI_GIAN_UPLOAD: "Thời gian upload",
  SO_CCCD_GAN_CHIP: "Số CCCD gắn chip",
  CHUONG_TRINH_VAY: "Chương trình vay",
  NHAP_GIA_SAU_VAT: "Nhập giá sau VAT",
  NHAP_SO_CHO_NGOI: "Nhập số chỗ ngồi",
  TRINH_DO_HOC_VAN: "Trình độ học vấn",
  THUONG_TRU_MA_QR: "thường trú ( Mã QR )",
  NHAP_TEN_CONG_TY: "Nhập tên công ty",
  CHON_MOI_QUAN_HE: "Chọn mối quan hệ",
  TEN_GOI_BAO_HIEM: "Tên gói bảo hiểm",
  DA_CO_LOI_XAY_RA: "Đã có lỗi xảy ra",
  CHON_TINH_THANH: "Chọn tỉnh / thành",
  CHON_QUAN_HUYEN: "Chọn quận / huyện",
  TY_LE_TRA_TRUOC: "Tỷ lệ trả trước",
  SO_TIEN_VAY_GOC: "Số tiền vay gốc",
  CHON_KY_HAN_VAY: "Chọn kỳ hạn vay",
  NGUOI_PHU_THUOC: "Người phụ thuộc",
  KET_QUA_DTI_MOI: "Kết quả DTI mới",
  CHU_KY_BAO_HIEM: "Chu kỳ bảo hiểm",
  NHAP_SO_CMND_CU: "Nhập số CMND cũ",
  HO_SO_CHO_XU_LY: "Hồ sơ chờ xử lý",
  YEU_CAU_BO_SUNG: "Yêu cầu bổ sung",
  TINH_THANH_PHO: "Tỉnh / Thành phố",
  CHON_PHUONG_XA: "Chọn phường / xã",
  NOI_O_HIEN_TAI: "Nơi ở hiện tại",
  NHAP_HO_VA_TEN: "Nhập họ và tên",
  CHON_GIOI_TINH: "Chọn giới tính",
  CHON_NGAY_SINH: "Chọn ngày sinh",
  TEN_NOI_BAN_XE: "Tên nơi bán xe",
  CHON_NGAN_HANG: "Chọn ngân hàng",
  CHON_CHI_NHANH: "Chọn chi nhánh",
  TONG_KHOAN_VAY: "Tổng khoản vay",
  KHOI_TAO_HO_SO: "Khởi tạo hồ sơ",
  NGUOI_YEU_CAU: "Người yêu cầu",
  NGAY_KHOI_TAO: "Ngày khởi tạo",
  THU_NHAP_KHAC: "Thu nhập khác",
  LOAI_CHUNG_TU: "Loại chứng từ",
  CHON_NGAY_CAP: "Chọn ngày cấp",
  TAI_NGAN_HANG: "Tại ngân hàng",
  NHAP_SO_LUONG: "Nhập số lượng",
  NHAP_SO_THANG: "Nhập số tháng",
  SO_DIEN_THOAI: "Số điện thoại",
  TIEP_TUC_NHAP: "Tiếp tục nhập",
  XEM_QUY_TRINH: "Xem quy trình",
  BO_SUNG_HO_SO: "Bổ sung hồ sơ",
  LOAI_BAO_HIEM: "Loại bảo hiểm",
  CHON_CHUC_VU: "Chọn chức vụ",
  CHUNG_TU_LOI: "Chứng từ lỗi",
  TEP_DINH_KEM: "Tệp đính kèm",
  NGUOI_UPLOAD: "Người upload",
  NOI_CAP_CCCD: "Nơi cấp CCCD",
  SAN_PHAM_VAY: "Sản phẩm vay",
  GIA_CHUA_VAT: "Giá chưa VAT",
  SO_TAI_KHOAN: "Số tài khoản",
  NHA_SAN_XUAT: "Nhà sản xuất",
  TEN_HANG_HOA: "Tên hàng hoá",
  NAM_SAN_XUAT: "Năm sản xuất",
  NHAP_MAU_SAC: "Nhập màu sắc",
  MUC_DICH_VAY: "Mục đích vay",
  KHOAN_VAY_CU: "khoản vay cũ",
  NHAP_SO_TIEN: "Nhập số tiền",
  THEM_GHI_CHU: "Thêm ghi chú",
  DIEM_DTI_MOI: "Điểm DTI mới",
  NHA_CUNG_CAP: "Nhà cung cấp",
  NGAY_HET_HAN: "Ngày hết hạn",
  NGUOI_XU_LY: "Người xử lý",
  NGHE_NGHIEP: "Nghề nghiệp",
  NO_VAY_KHAC: "Nợ vay khác",
  CHON_DAI_LY: "Chọn đại lý",
  GIA_SAU_VAT: "Giá sau VAT",
  SO_CHO_NGOI: "Số chỗ ngồi",
  KET_QUA_DTI: "Kết quả DTI",
  MOI_QUAN_HE: "Mối quan hệ",
  NHAP_KY_HAN: "Nhập kỳ hạn",
  XEM_BAO_CAO: "Xem báo cáo",
  TOI_CAM_KET: "Tôi cam kết",
  TRANG_THAI: "Trạng thái",
  QUAN_HUYEN: "Quận / Huyện",
  KY_HAN_VAY: "Kỳ hạn vay",
  TRONG_CHIP: "trong chip",
  PHUONG_XA: "Phường xã",
  CHI_NHANH: "Chi nhánh",
  HUY_HO_SO: "Hủy hồ sơ",
  CONG_VIEC: "Công việc",
  THONG_BAO: "Thông báo",
  HO_VA_TEN: "Họ và tên",
  GIOI_TINH: "Giới tính",
  NGAY_SINH: "Ngày sinh",
  QUOC_TICH: "Quốc tịch",
  NO_REPORT: "No Report",
  NHAP_VAT: "Nhập VAT",
  SO_LUONG: "Số lượng",
  BAO_HIEM: "Bảo hiểm",
  DIEM_DTI: "Điểm DTI",
  XAC_NHAN: "Xác nhận",
  HANG_HOA: "Hàng hoá",
  QUAY_LAI: "Quay lại",
  QUE_QUAN: "Quê quán",
  NGAY_CAP: "Ngày cấp",
  CHUC_VU: "Chức vụ",
  DIA_CHI: "Địa chỉ",
  MAU_SAC: "Màu sắc",
  GHI_CHU: "Ghi chú",
  AP_DUNG: "Áp dụng",
  SO_CCCD: "Số CCCD",
  DAI_LY: "Đại lý",
  KY_HAN: "Kỳ hạn",
  UPLOAD: "Upload",
  THANG: "Tháng",
  THOAT: "Thoát",
  KHAC: "Khác",
  EKYC: "eKYC",
  DONG: "Đóng",
  NAM: "Năm",
  VAT: "VAT",
  LUU: "Lưu",
  GUI: "Gửi",
  XOA: "Xóa",
  KYC: "KYC",
  CIC: "CIC",
};
