/* eslint-disable import/no-anonymous-default-export */
export default {
  THONG_TIN_DINH_DANH_CA_NHAN: "Thông tin định danh cá nhân",
  DIA_CHI_THUONG_TRU: "Địa chỉ thường trú",
  NHAP_DIA_CHI_THUONG_TRU: "Nhập địa chỉ thường trú",
  VUI_LONG_NHAP_DIA_CHI_THUONG_TRU: "Vui lòng nhập địa chỉ thường trú",
  CHON_TINH_THANH: "Chọn tỉnh / thành",
  TINH_THANH_PHO: "Tỉnh / Thành phố",
  CHON_QUAN_HUYEN: "Chọn quận / huyện",
  QUAN_HUYEN: "Quận / Huyện",
  CHON_PHUONG_XA: "Chọn phường / xã",
  PHUONG_XA: "Phường xã",
  DIA_CHI_THUONG_TRU_GIONG_VOI_NOI_O_HIEN_TAI: "Địa chỉ thường trú giống với nơi ở hiện tại",
  NOI_O_HIEN_TAI: "Nơi ở hiện tại",
  NHAP_NOI_O_HIEN_TAI: "Nhập nơi ở hiện tại",
  VUI_LONG_NHAP_NOI_O_HIEN_TAI: "Vui lòng nhập nơi ở hiện tại",
  THOI_GIAN_CU_TRU: "Thời gian cư trú",
  VUI_LONG_NHAP_NAM_CU_TRU: "Vui lòng nhập năm cư trú",
  VUI_LONG_NHAP_THANG_CU_TRU: "Vui lòng nhập tháng cư trú",
  THANG: "Tháng",
  NAM: "Năm",
  CHON_TINH_TRANG_CU_TRU: "Chọn tình trạng cư trú",
  TINH_TRANG_CU_TRU: "Tình trạng cư trú",
  CHON_NGHE_NGHIEP: "Chọn nghề nghiệp",
  NGHE_NGHIEP: "Nghề nghiệp",
  TEN_CONG_TY_NOI_LAM_VIEC: "Tên công ty/Nơi làm việc",
  NHAP_TEN_CONG_TY_NOI_LAM_VIEC: "Nhập tên công ty/Nơi làm việc",
  VUI_LONG_NHAP_TEN_CONG_TY_NOI_LAM_VIEC: "Vui lòng nhập tên công ty/Nơi làm việc",
  DIA_CHI_NOI_LAM_VIEC: "Địa chỉ nơi làm việc",
  NHAP_DIA_CHI_NOI_LAM_VIEC: "Nhập địa chỉ nơi làm việc",
  VUI_LONG_NHAP_DIA_CHI_NOI_LAM_VIEC: "Vui lòng nhập địa chỉ nơi làm việc",
  CHON_CHUC_VU: "Chọn chức vụ",
  CHUC_VU: "Chức vụ",
  SO_DIEN_THOAI_CONG_TY: "Số điện thoại công ty",
  NHAP_SO_DIEN_THOAI_CONG_TY: "Nhập số điện thoại công ty",
  VUI_LONG_NHAP_SO_DIEN_THOAI_CONG_TY: "Vui lòng nhập số điện thoại công ty",
  THU_NHAP_HANG_THANG: "Thu nhập hàng tháng",
  NHAP_THU_NHAP_HANG_THANG: "Nhập thu nhập hàng tháng",
  VUI_LONG_NHAP_THU_NHAP_HANG_THANG: "Vui lòng nhập thu nhập hàng tháng",
  CHI_PHI_SINH_HOAT: "Chi phí sinh hoạt",
  NHAP_CHI_PHI_SINH_HOAT: "Nhập chi phí sinh hoạt",
  VUI_LONG_NHAP_CHI_PHI_SINH_HOAT: "Vui lòng nhập chi phí sinh hoạt",
  NGUON_THU_NHAP_KHAC: "Nguồn thu nhập khác",
  NO_VAY_KHAC: "Nợ vay khác",
  THU_NHAP_KHAC: "Thu nhập khác",
  NHAP_THU_NHAP_KHAC: "Nhập thu nhập khác",
  VUI_LONG_NHAP_THU_NHAP_KHAC: "Vui lòng nhập thu nhập khác",
  CHON_NGHE_NGHIEP_CUA_THU_NHAP_KHAC: "Chọn nghề nghiệp của thu nhập khác",
  NGHE_NGHIEP_CUA_THU_NHAP_KHAC: "Nghề nghiệp của thu nhập khác",
  TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Tổng thanh toán nợ vay hàng tháng",
  NHAP_TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Nhập tổng thanh toán nợ vay hàng tháng",
  VUI_LONG_NHAP_TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Vui lòng nhập tổng thanh toán nợ vay hàng tháng",
  CHUNG_TU_LOI: "Chứng từ lỗi",
  VUI_LONG_TAI_LEN_FILE: "Vui lòng tải lên file",
  LOAI_CHUNG_TU: "Loại chứng từ",
  TEP_DINH_KEM: "Tệp đính kèm",
  NGUOI_UPLOAD: "Người upload",
  THOI_GIAN_UPLOAD: "Thời gian upload",
  FILE_UPLOAD_CO_DINH_DANG_JPG_JPEG_PNG_PDF_VA_KHONG_VUOT_QUA_5MB: "File upload có định dạng .jpg, .jpeg, .png, .pdf và không vượt quá 5MB",
  DUNG_LUONG_TOI_DA_CHO_PHEP_5MB: "Dung lượng tối đa cho phép 5MB",
  VUI_LONG_KIEM_TRA_LAI: "Vui lòng kiểm tra lại",
  DINH_DANG_FILE_CHO_PHEP: "Định dạng file cho phép",
  NHAP_HO_VA_TEN: "Nhập họ và tên",
  CHON_GIOI_TINH: "Chọn giới tính",
  CHON_NGAY_SINH: "Chọn ngày sinh",
  SO_DIEN_THOAI_DI_DONG: "Số điện thoại di động",
  NHAP_SO_DIEN_THOAI_DI_DONG: "Nhập số điện thoại di động",
  SO_CCCD_GAN_CHIP: "Số CCCD gắn chip",
  CHON_NGAY_CAP: "Chọn ngày cấp",
  CHON_NGAY_HET_HAN: "Chọn ngày hết hạn",
  NOI_CAP_CCCD: "Nơi cấp CCCD",
  CHON_NOI_CAP_CCCD: "Chọn nơi cấp CCCD",
  DIA_CHI: "Địa chỉ",
  CHUONG_TRINH_VAY_VA_SAN_PHAM: "Chương trình vay và sản phẩm",
  NHOM_SAN_PHAM_VAY: "Nhóm sản phẩm vay",
  SAN_PHAM_VAY: "Sản phẩm vay",
  DAI_LY: "Đại lý",
  VUI_LONG_CHON_DAI_LY: "Vui lòng chọn đại lý",
  CHON_DAI_LY: "Chọn đại lý",
  CHON_CHUONG_TRINH_VAY: "Chọn chương trình vay",
  CHUONG_TRINH_VAY: "Chương trình vay",
  TY_LE_TRA_TRUOC_TOI_THIEU_CHO_CHUONG_TRINH_VAY_LA_MINIMUMPREPAYMENTPERCENT_: "Tỷ lệ trả trước tối thiểu cho chương trình vay là {{minimumPrepaymentPercent}} %",
  TY_LE_TRA_TRUOC_TOI_DA_CHO_CHUONG_TRINH_VAY_LA_MAXIMUMPREPAYMENTPERCENT_: "Tỷ lệ trả trước tối đa cho chương trình vay là {{maximumPrepaymentPercent}} %",
  SO_TIEN_VAY_GOC_TOI_THIEU_CUA_CHUONG_TRINH_VAY_LA_MINIMUMLOANAMOUNT_VND: "Số tiền vay gốc tối thiểu của chương trình vay là: {{minimumLoanAmount}} VND",
  SO_TIEN_VAY_GOC_TOI_DA_CUA_CHUONG_TRINH_VAY_LA_MAXIMUMLOANAMOUNT_VND: "Số tiền vay gốc tối đa của chương trình vay là: {{maximumLoanAmount}} VND",
  THONG_TIN_HOP_DONG_MUA_BAN: "Thông tin hợp đồng mua bán",
  TEN_NOI_BAN_XE: "Tên nơi bán xe",
  NHAP_TEN_NOI_BAN_XE: "Nhập tên nơi bán xe",
  SO_HOP_DONG_MUA_BAN: "Số hợp đồng mua bán",
  NHAP_SO_HOP_DONG_MUA_BAN: "Nhập Số hợp đồng mua bán",
  NGAY_KI_HOP_DONG_MUA_BAN: "Ngày kí hợp đồng mua bán",
  SO_HOP_DONG_UY_QUYEN: "Số hợp đồng ủy quyền",
  NHAP_SO_HOP_DONG_UY_QUYEN: "Nhập Số hợp đồng ủy quyền",
  GIA_CHUA_VAT: "Giá chưa VAT",
  NHAP_GIA_CHUA_VAT: "Nhập giá chưa VAT",
  VAT: "VAT",
  NHAP_VAT: "Nhập VAT",
  GIA_SAU_VAT: "Giá sau VAT",
  NHAP_GIA_SAU_VAT: "Nhập giá sau VAT",
  SO_CHO_NGOI: "Số chỗ ngồi",
  NHAP_SO_CHO_NGOI: "Nhập số chỗ ngồi",
  SO_TAI_KHOAN: "Số tài khoản",
  NHAP_SO_TAI_KHOAN: "Nhập số tài khoản",
  TAI_NGAN_HANG: "Tại ngân hàng",
  CHON_NGAN_HANG: "Chọn ngân hàng",
  CHI_NHANH: "Chi nhánh",
  CHON_CHI_NHANH: "Chọn chi nhánh",
  THONG_TIN_HANG_HOA: "Thông tin hàng hóa",
  GIA_BAN_TOI_DA_LA_MAXPRICE_VND: "Giá bán tối đa là {{maxPrice}} VND",
  CHON_NHA_SAN_XUAT: "Chọn nhà sản xuất",
  NHA_SAN_XUAT: "Nhà sản xuất",
  CHON_TEN_HANG_HOA: "Chọn Tên hàng hoá",
  TEN_HANG_HOA: "Tên hàng hoá",
  NAM_SAN_XUAT: "Năm sản xuất",
  MAU_SAC: "Màu sắc",
  NHAP_MAU_SAC: "Nhập màu sắc",
  SO_LUONG: "Số lượng",
  NHAP_SO_LUONG: "Nhập số lượng",
  TONG_GIA_HANG_HOA: "Tổng giá hàng hóa",
  THONG_TIN_KHOAN_VAY: "Thông tin khoản vay",
  TY_LE_TRA_TRUOC: "Tỷ lệ trả trước",
  VUI_LONG_NHAP_TY_LE_TRA_TRUOC: "Vui lòng nhập tỷ lệ trả trước",
  DON_GIA_CUA_TITLE_: "Đơn giá (của {{title}})",
  SO_TIEN_TRA_TRUOC: "Số tiền trả trước",
  VUI_LONG_NHAP_SO_TIEN_TRA_TRUOC: "Vui lòng nhập số tiền trả trước",
  NGAY_KY_HOP_DONG_DU_KIEN: "Ngày ký hợp đồng dự kiến",
  VUI_LONG_CHON_NGAY_KY_HOP_DONG_DU_KIEN: "Vui lòng chọn ngày ký hợp đồng dự kiến",
  NGAY_THANH_TOAN_HANG_THANG: "Ngày thanh toán hàng tháng",
  VUI_LONG_CHON_NGAY_THANH_TOAN: "Vui lòng chọn ngày thanh toán",
  CHON_NGAY_THANH_TOAN: "Chọn ngày thanh toán",
  SO_TIEN_VAY_GOC: "Số tiền vay gốc",
  KY_HAN_VAY: "Kỳ hạn vay",
  VUI_LONG_CHON_KY_HAN_VAY: "Vui lòng chọn kỳ hạn vay",
  CHON_KY_HAN_VAY: "Chọn kỳ hạn vay",
  MUC_DICH_VAY: "Mục đích vay",
  VUI_LONG_CHON_MUC_DICH_VAY: "Vui lòng chọn mục đích vay",
  CHON_MUC_DICH_VAY: "Chọn mục đích vay",
  KHOAN_VAY_CU: "khoản vay cũ",
  KHACH_HANG_THUC_HIEN_THANH_TOAN: "Khách hàng thực hiện thanh toán",
  KY_HAN_GIAI_DOAN_1: "Kỳ hạn giai đoạn 1",
  LAI_SUAT_GIAI_DOAN_1: "Lãi suất giai đoạn 1",
  KY_HAN_GIAI_DOAN_2: "Kỳ hạn giai đoạn 2",
  LAI_SUAT_GIAI_DOAN_2: "Lãi suất giai đoạn 2",
  SO_TIEN_THANH_TOAN_HANG_THANG_GIAI_DOAN_1: "Số tiền thanh toán hàng tháng giai đoạn 1",
  SO_TIEN_THANH_TOAN_HANG_THANG_GIAI_DOAN_2: "Số tiền thanh toán hàng tháng giai đoạn 2",
  BAO_HIEM: "Bảo hiểm",
  THEM_BAO_HIEM_TU_NGUYEN: "Thêm bảo hiểm tự nguyện",
  TONG_SO_TIEN_VAY_MUA_BAO_HIEM: "Tổng số tiền vay mua bảo hiểm",
  TONG_KHOAN_VAY: "Tổng khoản vay",
  THONG_TIN_KHACH_HANG_BO_SUNG: "Thông tin khách hàng bổ sung",
  TEN_THUONG_GOI_O_NHA: "Tên thường gọi ở nhà",
  NHAP_TEN_TEN_GOI_O_NHA: "Nhập tên tên gọi ở nhà",
  TRINH_DO_HOC_VAN: "Trình độ học vấn",
  VUI_LONG_CHON_TRINH_DO_HOC_VAN: "Vui lòng chọn trình độ học vấn",
  CHON_TRINH_DO_HOC_VAN: "Chọn trình độ học vấn",
  DIA_CHI_THUONG_TRU_TRUNG_VOI_DIA_CHI: "Địa chỉ thường trú trùng với địa chỉ",
  THUONG_TRU_MA_QR_: "thường trú ( Mã QR )",
  TRONG_CHIP: "trong chip",
  VUI_LONG_CHON_TINH_THANH_PHO: "Vui lòng chọn tỉnh/ thành phố",
  CHON_TINH_THANH_PHO: "Chọn tỉnh/ thành phố",
  VUI_LONG_CHON_QUAN_HUYEN: "Vui lòng chọn quận/ huyện",
  VUI_LONG_CHON_PHUONG_XA: "Vui lòng chọn phường / xã",
  VUI_LONG_NHAP_SO_NAM: "Vui lòng nhập số năm",
  VUI_LONG_NHAP_SO_THANG: "Vui lòng nhập số tháng",
  NHAP_SO_THANG: "Nhập số tháng",
  VUI_LONG_CHON_TINH_TRANG_CU_TRU: "Vui lòng chọn tình trạng cư trú",
  CONG_VIEC_KHACH_HANG: "Công việc khách hàng",
  VUI_LONG_CHON_NGHE_NGHIEP: "Vui lòng chọn nghề nghiệp",
  NHAP_TEN_CONG_TY: "Nhập tên công ty",
  VUI_LONG_NHAP_TEN_CONG_TY: "Vui lòng nhập tên công ty",
  VUI_LONG_CHON_CHUC_VU: "Vui lòng chọn chức vụ",
  CHON_CHON_CHUC_VU: "Chọn chọn chức vụ",
  THOI_GIAN_LAM_VIEC: "Thời gian làm việc",
  VUI_LONG_NHAP_NAM_LAM_VIEC: "Vui lòng nhập năm làm việc",
  VUI_LONG_NHAP_THANG_LAM_VIEC: "Vui lòng nhập tháng làm việc",
  TAI_CHINH_KHACH_HANG: "Tài chính khách hàng",
  CHI_PHI_SINH_HOAT_HANG_THANG: "Chi phí sinh hoạt hàng tháng",
  NHAP_CHI_PHI_SINH_HOAT_HANG_THANG: "Nhập chi phí sinh hoạt hàng tháng",
  VUI_LONG_NHAP_CHI_PHI_SINH_HOAT_HANG_THANG: "Vui lòng nhập chi phí sinh hoạt hàng tháng",
  NGUOI_PHU_THUOC: "Người phụ thuộc",
  KHOAN_THANH_TOAN_NO_VAY_HANG_THANG: "Khoản thanh toán nợ vay hàng tháng",
  VUI_LONG_NHAP_SO_TIEN: "Vui lòng nhập số tiền",
  NHAP_SO_TIEN: "Nhập số tiền",
  SO_NGUOI_PHU_THUOC: "Số người phụ thuộc",
  NHAP_SO_NGUOI_PHU_THUOC: "Nhập số người phụ thuộc",
  VUI_LONG_NHAP_SO_NGUOI_PHU_THUOC: "Vui lòng nhập số người phụ thuộc",
  DIEM_DTI: "Điểm DTI",
  KET_QUA_DTI: "Kết quả DTI",
  DE_XUAT_KHOAN_VAY: "Đề xuất khoản vay",
  THONG_TIN_NGUOI_LIEN_QUAN: "Thông tin người liên quan",
  NGUOI_LIEN_HE_TRONG_TRUONG_HOP_THUC_HIEN_NGHIA_VU_THEO_HOP_DONG: "Người liên hệ trong trường hợp thực hiện nghĩa vụ theo hợp đồng",
  VUI_LONG_NHAP_HO_VA_TEN: "Vui lòng nhập họ và tên",
  MOI_QUAN_HE: "Mối quan hệ",
  CHON_MOI_QUAN_HE: "Chọn mối quan hệ",
  VUI_LONG_CHON_MOI_QUAN_HE: "Vui lòng chọn mối quan hệ",
  SO_DIEN_THOAI: "Số điện thoại",
  NHAP_SO_DIEN_THOAI: "Nhập số điện thoại",
  VUI_LONG_NHAP_SO_DIEN_THOAI: "Vui lòng nhập số điện thoại",
  NGUOI_LIEN_HE_TRONG_TRUONG_HOP_KHAN_CAP: "Người liên hệ trong trường hợp khẩn cấp",
  VUI_LONG_UPLOAD_FILE: "Vui lòng upload file",
  HAY_CHON_LOAI_CHUNG_TU: "Hãy chọn loại chứng từ",
  THEM_CHUNG_TU_BO_SUNG: "Thêm chứng từ bổ sung",
  FILE_TAI_LEN_CO_DINH_DANG_PDF_HOAC_HINH_ANH_JPG_JPEG_PNG_VA_KHONG_VUOT_QUA_5MB: "File tải lên có định dạng .pdf hoặc hình ảnh .jpg, .jpeg, .png và không vượt quá 5MB",
  _DOC_DOCX_XLS_XLSX_JPG_JPEG_PNG_PDF_: ".doc, .docx,.xls, .xlsx, .jpg, .jpeg, .png, .pdf.",
  GHI_CHU: "Ghi chú",
  CHUNG_TU_DINH_KEM: "Chứng từ đính kèm",
  THEM_GHI_CHU: "Thêm ghi chú",
  HUY_HO_SO: "Hủy hồ sơ",
  THOAT: "Thoát",
  LUU: "Lưu",
  GUI: "Gửi",
  THOI_GIAN_LAM_VIEC_DA_HET: "Thời gian làm việc đã hết",
  XAC_NHAN: "Xác nhận",
  DA_HET_GIO_LAM_VIEC_VUI_LONG_THUC_HIEN_THAO_TAC_TRONG_KHOANG_THOI_GIAN_TU_STARTTIME_DEN_ENDTIME_: "Đã hết giờ làm việc, vui lòng thực hiện thao tác trong khoảng thời gian từ {{startTime}} đến {{endTime}}",
  GIA_DINH_KET_QUA_DTI: "Giả định kết quả DTI",
  DIEM_DTI_HIEN_TAI: "Điểm DTI hiện tại",
  NHAP_KY_HAN: "Nhập kỳ hạn",
  KY_HAN: "Kỳ hạn",
  DIEM_DTI_MOI: "Điểm DTI mới",
  KET_QUA_DTI_MOI: "Kết quả DTI mới",
  AP_DUNG: "Áp dụng",
  THONG_TIN_EKYC_KHACH_HANG: "Thông tin eKYC khách hàng",
  THONG_TIN_NGUOI_HON_PHOI: "Thông tin người hôn phối",
  CONG_VIEC: "Công việc",
  HANG_HOA: "Hàng hoá",
  KHAC: "Khác",
  DO_TUOI_KHACH_HANG_KHONG_DAT_DO_TUOI_TOI_THIEU_CUA_CHUONG_TRINH_VAY: "Độ tuổi khách hàng không đạt độ tuổi tối thiểu của chương trình vay",
  DO_TUOI_KHACH_HANG_VUOT_QUA_DO_TUOI_TOI_DA_CUA_CHUONG_TRINH_VAY: "Độ tuổi khách hàng vượt quá độ tuổi tối đa của chương trình vay",
  VUI_LONG_NHAP_DAY_DU_CAC_THONG_TIN_BAT_BUOC: "Vui lòng nhập đầy đủ các thông tin bắt buộc",
  NGAY_HET_HAN_PHAI_LON_HON_NGAY_HIEN_TAI: "Ngày hết hạn phải lớn hơn ngày hiện tại",
  NAM_SINH_KHONG_TRUNG_KHOP_VOI_CCCD: "Năm sinh không trùng khớp với CCCD",
  NGAY_CAP_KHONG_DUOC_LON_HON_NGAY_HIEN_TAI: "Ngày cấp không được lớn hơn ngày hiện tại",
  NGAY_CAP_KHONG_DUOC_NHO_HON_NGAY_HET_HAN_CUA_CCCD: "Ngày cấp không được nhỏ hơn ngày hết hạn của CCCD",
  GIOI_TINH_KHONG_TRUNG_KHOP_VOI_CCCD: "Giới tính không trùng khớp với CCCD",
  NGAY_SINH_KHONG_DUOC_LON_HON_NGAY_CAP: "Ngày sinh không được lớn hơn ngày cấp",
  SO_DIEN_THOAI_CUA_2_NGUOI_LIEN_HE_KHONG_DUOC_GIONG_NHAU: "Số điện thoại của 2 người liên hệ không được giống nhau",
  SO_DIEN_THOAI_KHACH_HANG_KHONG_DUOC_TRUNG_VOI_SO_DIEN_THOAI_NGUOI_LIEN_HE: "Số điện thoại khách hàng không được trùng với số điện thoại người liên hệ",
  NGAY_KY_HOP_DONG_PHAI_LON_HON_HOAC_BANG_NGAY_HIEN_TAI: "Ngày ký hợp đồng phải lớn hơn hoặc bằng ngày hiện tại",
  LOI_VUI_LONG_THU_LAI_SAU_IT_PHUT: "Lỗi, vui lòng thử lại sau ít phút",
  BAO_HIEM_DUA_TREN_KHA_NANG_TAI_CHINH_KHACH_HANG: "Bảo hiểm dựa trên khả năng tài chính khách hàng",
  BAO_HIEM_TU_NGUYEN: "Bảo hiểm tự nguyện",
  XOA: "Xóa",
  NHA_CUNG_CAP: "Nhà cung cấp",
  VUI_LONG_CHON_NHA_CUNG_CAP: "Vui lòng chọn nhà cung cấp",
  CHON_NHA_CUNG_CAP: "Chọn nhà cung cấp",
  TEN_GOI_BAO_HIEM: "Tên gói bảo hiểm",
  CHON_TEN_GOI_BAO_HIEM: "Chọn tên gói bảo hiểm",
  HINH_THUC_THANH_TOAN: "Hình thức thanh toán",
  VUI_LONG_CHON_HINH_THUC_THANH_TOAN: "Vui lòng chọn hình thức thanh toán",
  CHON_HINH_THUC_THANH_TOAN: "Chọn hình thức thanh toán",
  CHU_KY_BAO_HIEM: "Chu kỳ bảo hiểm",
  TY_LE_PHI_BAO_HIEM_THEO_THANG: "Tỷ lệ phí bảo hiểm theo tháng",
  PHI_BAO_HIEM_TAM_TINH_VND_: "Phí bảo hiểm tạm tính (VND)",
  SO_TIEN_BAO_HIEM_TAM_TINH_VND_: "Số tiền bảo hiểm tạm tính (VND)",
  TONG_SO_TIEN_VAY_VA_DU_NO_HIEN_TAI_CUA_KHACH_HANG_KHONG_VUOT_QUA_: "Tổng số tiền vay và dư nợ hiện tại của khách hàng không vượt quá ",
  CHON_LY_DO_TU_CHOI: "Chọn lý do từ chối",
  VUI_LONG_CHON_LY_DO_TU_CHOI: "Vui lòng chọn lý do từ chối",
  DIA_CHI_THUONG_TRU_KHONG_DAY_DU_DU_LIEU_VUI_LONG_NHAP_THONG_TIN_DIA_CHI_HIEN_TAI: "Địa chỉ thường trú không đầy đủ dữ liệu. Vui lòng nhập thông tin địa chỉ hiện tại",
  DIEM_DTI_KHONG_DAT_VUI_LONG_DIEU_CHINH_KHOAN_VAY_HOAC_KY_HAN_PHU_HOP: "Điểm DTI không đạt. Vui lòng điều chỉnh khoản vay hoặc kỳ hạn phù hợp",
  THONG_BAO: "Thông báo",
  HUY_BO_SUNG_HO_SO: "Hủy bổ sung hồ sơ",
  CAC_THONG_TIN_DA_NHAP_SE_KHONG_DUOC_LUU_LAI: "Các thông tin đã nhập sẽ không được lưu lại",
  TIEP_TUC_NHAP: "Tiếp tục nhập",
  HIEN_TAI_QUY_KHACH_CHUA_DU_DIEU_KIEN_VAY_TAI_JIVF_CAM_ON_QUY_KHACH_DA_QUAN_TAM_DEN_DICH_VU_CUA_CHUNG_TOI: "Hiện tại Quý khách chưa đủ điều kiện vay tại JIVF. Cảm ơn Quý khách đã quan tâm đến dịch vụ của chúng tôi",
  PCB_CIC_KHONG_CO_PHAN_HOI_VUI_LONG_GUI_LAI_HO_SO_DE_TRA_CUU_LAI_HOAC_THOAT: "PCB/CIC không có phản hồi, vui lòng gửi lại hồ sơ để tra cứu lại hoặc thoát",
  TONG_KHOAN_VAY_DE_XUAT_VA_DU_NO_TIN_CHAP_HIEN_TAI_CUA_KHACH_HANG_KHONG_DUOC_VUOT_QUA_CHECKTOTALLOAN_VND_VUI_LONG_DIEU_CHINH_SO_TIEN_TRA_TRUOC_HOAC_HUONG_DAN_KHACH_HANG_THANH_TOAN_KHOAN_VAY_CU: "Tổng khoản vay đề xuất và Dư nợ tín chấp hiện tại của khách hàng không được vượt quá {{checkTotalLoan}} VND. Vui lòng điều chỉnh Số tiền trả trước hoặc hướng dẫn khách hàng thanh toán khoản vay cũ",
  TEP_TAI_LEN_QUA_LON: "Tệp tải lên quá lớn",
  NHAN_VIEN_TU_VAN_XAC_NHAN_DA_KIEM_TRA_VA_CHIU_TRACH_NHIEM_VE_TINH_CHINH_XAC_CUA_CAC_THONG_TIN_KHACH_HANG_CUNG_CAP_DONG_THOI_TUAN_THU_NOI_DUNG_VE_CAC_HANH_VI_BI_CAM_VA_CAC_LUU_Y_BAT_BUOC_TUAN_THU_KHI_THUC_HIEN_CONG_VIEC_CUA_JIVF_: "Nhân viên Tư vấn xác nhận đã kiểm tra và chịu trách nhiệm về tính chính xác của các thông tin Khách hàng cung cấp; đồng thời tuân thủ nội dung về “Các hành vi bị cấm và các lưu ý bắt buộc tuân thủ khi thực hiện công việc” của JIVF.",
  QUAY_LAI: "Quay lại",
  DA_CO_LOI_XAY_RA: "Đã có lỗi xảy ra",
  HO_VA_TEN: "Họ và tên",
  GIOI_TINH: "Giới tính",
  NGAY_SINH: "Ngày sinh",
  SO_CMND_DA_DUOC_CAP: "Số CMND đã được cấp",
  NHAP_SO_CMND_CU: "Nhập số CMND cũ",
  VUI_LONG_NHAP_DUNG_SO_CMND_HOAC_LIEN_HE_BO_PHAN_KINH_DOANH_DE_DUOC_HUONG_DAN: "Vui lòng nhập đúng số CMND hoặc liên hệ bộ phận kinh doanh để được hướng dẫn",
  VUI_LONG_NHAP_DUNG_DINH_DANG_CUA_CMND: "Vui lòng nhập đúng định dạng của CMND",
  QUOC_TICH: "Quốc tịch",
  QUE_QUAN: "Quê quán",
  SO_CCCD: "Số CCCD",
  NGAY_CAP: "Ngày cấp",
  NGAY_HET_HAN: "Ngày hết hạn",
}
