export default {
  NHAN_VIEN_TU_VAN_XAC_NHAN_DA_KIEM_TRA_VA_CHIU_TRACH_NHIEM_VE_TINH_CHINH_XAC_CUA_CAC_THONG_TIN_KHACH_HANG_CUNG_CAP_DONG_THOI_TUAN_THU_NOI_DUNG_VE_CAC_HANH_VI_BI_CAM_VA_CAC_LUU_Y_BAT_BUOC_TUAN_THU_KHI_THUC_HIEN_CONG_VIEC_CUA_JIVF: "Nhân viên Tư vấn xác nhận đã kiểm tra và chịu trách nhiệm về tính chính xác của các thông tin Khách hàng cung cấp; đồng thời tuân thủ nội dung về “Các hành vi bị cấm và các lưu ý bắt buộc tuân thủ khi thực hiện công việc” của JIVF.",
  TONG_KHOAN_VAY_DE_XUAT_VA_DU_NO_TIN_CHAP_HIEN_TAI_CUA_KHACH_HANG_KHONG_DUOC_VUOT_QUA_CHECKTOTALLOAN_VND_VUI_LONG_DIEU_CHINH_SO_TIEN_TRA_TRUOC_HOAC_HUONG_DAN_KHACH_HANG_THANH_TOAN_KHOAN_VAY_CU: "Tổng khoản vay đề xuất và Dư nợ tín chấp hiện tại của khách hàng không được vượt quá {{checkTotalLoan}} VND. Vui lòng điều chỉnh Số tiền trả trước hoặc hướng dẫn khách hàng thanh toán khoản vay cũ",
  NGAY_KY_HOP_DONG_DU_KIEN_KHONG_DUOC_NHO_HON_NGAY_HIEN_TAI_VUI_LONG_DIEU_CHINH_LAI_NGAY_KY_HOP_DONG_DU_KIEN: "Ngày ký hợp đồng dự kiến không được nhỏ hơn ngày hiện tại. Vui lòng điều chỉnh lại Ngày ký hợp đồng dự kiến",
  HIEN_TAI_QUY_KHACH_CHUA_DU_DIEU_KIEN_VAY_TAI_JIVF_CAM_ON_QUY_KHACH_DA_QUAN_TAM_DEN_DICH_VU_CUA_CHUNG_TOI: "Hiện tại Quý khách chưa đủ điều kiện vay tại JIVF. Cảm ơn Quý khách đã quan tâm đến dịch vụ của chúng tôi",
  DA_HET_GIO_LAM_VIEC_VUI_LONG_THUC_HIEN_THAO_TAC_TRONG_KHOANG_THOI_GIAN_TU_STARTTIME_DEN_ENDTIME: "Đã hết giờ làm việc, vui lòng thực hiện thao tác trong khoảng thời gian từ {{startTime}} đến {{endTime}}",
  NGUOI_HON_PHOI_CO_NO_NHOM_3_HOAC_NHOM_4_TRONG_VONG_36_THANG_GAN_NHAT_VA_NGOAI_24_THANG_GAN_NHAT: "Người hôn phối có nợ nhóm 3 hoặc nhóm 4 trong vòng 36 tháng gần nhất và ngoài 24 tháng gần nhất",
  KHACH_HANG_CO_NO_NHOM_3_HOAC_NHOM_4_TRONG_VONG_36_THANG_GAN_NHAT_VA_NGOAI_24_THANG_GAN_NHAT: "Khách hàng có nợ nhóm 3 hoặc nhóm 4 trong vòng 36 tháng gần nhất và ngoài 24 tháng gần nhất",
  DIA_CHI_THUONG_TRU_KHONG_DAY_DU_DU_LIEU_VUI_LONG_NHAP_THONG_TIN_DIA_CHI_HIEN_TAI: "Địa chỉ thường trú không đầy đủ dữ liệu. Vui lòng nhập thông tin địa chỉ hiện tại",
  FILE_TAI_LEN_CO_DINH_DANG_PDF_HOAC_HINH_ANH_JPG_JPEG_PNG_VA_KHONG_VUOT_QUA_5MB: "File tải lên có định dạng .pdf hoặc hình ảnh .jpg, .jpeg, .png và không vượt quá 5MB",
  VUI_LONG_NHAP_DUNG_SO_CMND_HOAC_LIEN_HE_BO_PHAN_KINH_DOANH_DE_DUOC_HUONG_DAN: "Vui lòng nhập đúng số CMND hoặc liên hệ bộ phận kinh doanh để được hướng dẫn",
  TY_LE_TRA_TRUOC_TOI_THIEU_CHO_CHUONG_TRINH_VAY_LA_MINIMUMPREPAYMENTPERCENT: "Tỷ lệ trả trước tối thiểu cho chương trình vay là {{minimumPrepaymentPercent}} %",
  PCB_CIC_KHONG_CO_PHAN_HOI_VUI_LONG_GUI_LAI_HO_SO_DE_TRA_CUU_LAI_HOAC_THOAT: "PCB/CIC không có phản hồi, vui lòng gửi lại hồ sơ để tra cứu lại hoặc thoát",
  VUI_LONG_TICH_CHON_TRE_HAN_KHONG_TRE_HAN_KHONG_XAC_DINH_CUA_NGUOI_HON_PHOI: "Vui lòng tích chọn Trễ hạn/Không trễ hạn/Không xác định của người hôn phối",
  SO_DIEN_THOAI_KHACH_HANG_KHONG_DUOC_TRUNG_VOI_SO_DIEN_THOAI_NGUOI_LIEN_HE: "Số điện thoại khách hàng không được trùng với số điện thoại người liên hệ",
  TY_LE_TRA_TRUOC_TOI_DA_CHO_CHUONG_TRINH_VAY_LA_MAXIMUMPREPAYMENTPERCENT: "Tỷ lệ trả trước tối đa cho chương trình vay là {{maximumPrepaymentPercent}} %",
  SO_TIEN_VAY_GOC_TOI_THIEU_CUA_CHUONG_TRINH_VAY_LA_MINIMUMLOANAMOUNT_VND: "Số tiền vay gốc tối thiểu của chương trình vay là: {{minimumLoanAmount}} VND",
  VUI_LONG_TICH_CHON_TRE_HAN_KHONG_TRE_HAN_KHONG_XAC_DINH_CUA_KHACH_HANG: "Vui lòng tích chọn Trễ hạn/Không trễ hạn/Không xác định của khách hàng",
  SO_TIEN_VAY_GOC_TOI_DA_CUA_CHUONG_TRINH_VAY_LA_MAXIMUMLOANAMOUNT_VND: "Số tiền vay gốc tối đa của chương trình vay là: {{maximumLoanAmount}} VND",
  DIEM_DTI_KHONG_DAT_VUI_LONG_DIEU_CHINH_KHOAN_VAY_HOAC_KY_HAN_PHU_HOP: "Điểm DTI không đạt. Vui lòng điều chỉnh khoản vay hoặc kỳ hạn phù hợp",
  KHOAN_THANH_TOAN_NO_VAY_HANG_THANG_TAI_TAT_CA_CAC_TCTD_BAO_GOM_JIVF_: "Khoản thanh toán nợ vay hàng tháng tại tất cả các TCTD (Bao gồm JIVF)",
  DO_TUOI_KHACH_HANG_KHONG_DAT_DO_TUOI_TOI_THIEU_CUA_CHUONG_TRINH_VAY: "Độ tuổi khách hàng không đạt độ tuổi tối thiểu của chương trình vay",
  NGUOI_LIEN_HE_TRONG_TRUONG_HOP_CAN_THUC_HIEN_NGHIA_VU_THEO_HOP_DONG: "Người liên hệ trong trường hợp cần thực hiện nghĩa vụ theo hợp đồng",
  TONG_SO_TIEN_VAY_VA_DU_NO_HIEN_TAI_CUA_KHACH_HANG_KHONG_VUOT_QUA: "Tổng số tiền vay và dư nợ hiện tại của khách hàng không vượt quá {{totalLoan}} VND",
  FILE_UPLOAD_CO_DINH_DANG_JPG_JPEG_PNG_PDF_VA_KHONG_VUOT_QUA_5MB: "File upload có định dạng .jpg, .jpeg, .png, .pdf và không vượt quá 5MB",
  NGUOI_LIEN_HE_TRONG_TRUONG_HOP_THUC_HIEN_NGHIA_VU_THEO_HOP_DONG: "Người liên hệ trong trường hợp thực hiện nghĩa vụ theo hợp đồng",
  DO_TUOI_KHACH_HANG_VUOT_QUA_DO_TUOI_TOI_DA_CUA_CHUONG_TRINH_VAY: "Độ tuổi khách hàng vượt quá độ tuổi tối đa của chương trình vay",
  DANG_TRUY_VAN_KET_QUA_TU_CIC_VUI_LONG_THUC_HIEN_LAI_SAU_IT_PHUT: "Đang truy vấn kết quả từ CIC. Vui lòng thực hiện lại sau ít phút",
  NGUOI_HON_PHOI_TRONG_3_THANG_GAN_NHAT_CO_LICH_SU_NO_CAN_CHU_Y: "Người hôn phối trong 3 tháng gần nhất có lịch sử nợ cần chú ý",
  NGUOI_HON_PHOI_CO_DU_NO_DA_BAN_CHO_CONG_TY_QUAN_LY_TAI_SAN: "Người hôn phối có dư nợ đã bán cho công ty quản lý tài sản",
  KHACH_HANG_TRONG_3_THANG_GAN_NHAT_CO_LICH_SU_NO_CAN_CHU_Y: "Khách hàng trong 3 tháng gần nhất có lịch sử nợ cần chú ý",
  NGUOI_HON_PHOI_CO_NO_TU_NHOM_5_TRONG_VONG_5_NAM_GAN_NHAT: "Người hôn phối có nợ từ nhóm 5 trong vòng 5 năm gần nhất",
  NGUOI_HON_PHOI_HIEN_TAI_DANG_CO_QUAN_HE_NHIEU_HON_4_TCTD: "Người hôn phối hiện tại đang có quan hệ nhiều hơn 4 TCTD",
  CHI_PHI_SINH_HOAT_HANG_THANG_SAU_KHI_SO_SANH_THEO_ADECCO: "Chi phí sinh hoạt hàng tháng sau khi so sánh theo Adecco",
  SO_DIEN_THOAI_CUA_2_NGUOI_LIEN_HE_KHONG_DUOC_GIONG_NHAU: "Số điện thoại của 2 người liên hệ không được giống nhau",
  VUI_LONG_TICH_CHON_TRE_HAN_KHONG_TRE_HAN_KHONG_XAC_DINH: "Vui lòng tích chọn Trễ hạn/Không trễ hạn/Không xác định",
  KHACH_HANG_CO_DU_NO_DA_BAN_CHO_CONG_TY_QUAN_LY_TAI_SAN: "Khách hàng có dư nợ đã bán cho công ty quản lý tài sản",
  NGAY_KY_HOP_DONG_PHAI_LON_HON_HOAC_BANG_NGAY_HIEN_TAI: "Ngày ký hợp đồng phải lớn hơn hoặc bằng ngày hiện tại",
  KHACH_HANG_CO_NO_TU_NHOM_5_TRONG_VONG_5_NAM_GAN_NHAT: "Khách hàng có nợ từ nhóm 5 trong vòng 5 năm gần nhất",
  KHACH_HANG_HIEN_TAI_DANG_CO_QUAN_HE_NHIEU_HON_4_TCTD: "Khách hàng hiện tại đang có quan hệ nhiều hơn 4 TCTD",
  VUI_LONG_TICH_CHON_CAC_THONG_TIN_HOP_LE_KHONG_HOP_LE: "Vui lòng tích chọn các thông tin Hợp lệ/Không hợp lệ",
  CHON_THONG_TIN_CAN_THU_THAP_KHI_THUC_HIEN_SITE_VISIT: "Chọn thông tin cần thu thập khi thực hiện site visit",
  DIA_CHI_SITE_VISIT_YEU_CAU_GHI_RO_SO_NHA_TEN_DUONG: "Địa chỉ site visit ( Yêu cầu ghi rõ: số nhà, tên đường)",
  NGAY_CAP_KHONG_DUOC_NHO_HON_NGAY_HET_HAN_CUA_CCCD: "Ngày cấp không được nhỏ hơn ngày hết hạn của CCCD",
  VUI_LONG_NHAP_GHI_CHU_Y_KIEN_PHE_DUYET_CHINH_THUC: "Vui lòng nhập ghi chú ý kiến phê duyệt chính thức",
  LICH_SU_TIN_DUNG_TAI_CAC_TCTD_CUA_NGUOI_HON_PHOI: "Lịch sử tín dụng tại các TCTD của người hôn phối",
  DA_CO_LOI_XAY_RA_KHI_TIM_KIEM_LICH_SU_KHACH_HANG: "Đã có lỗi xảy ra khi tìm kiếm lịch sử khách hàng",
  VUI_LONG_NHAP_TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Vui lòng nhập tổng thanh toán nợ vay hàng tháng",
  BAO_HIEM_DUA_TREN_KHA_NANG_TAI_CHINH_KHACH_HANG: "Bảo hiểm dựa trên khả năng tài chính khách hàng",
  BAO_CAO_SITE_VISIT_DANH_CHO_THAM_DINH_HO_SO_VAY: "Báo cáo site visit dành cho thẩm định hồ sơ vay",
  THONG_TIN_CAN_THU_THAP_KHI_THUC_HIEN_SITE_VISIT: "Thông tin cần thu thập khi thực hiện site visit",
  VUI_LONG_NHAP_GHI_CHU_THAM_DINH_QUA_DIEN_THOAI: "Vui lòng nhập ghi chú thẩm định qua điện thoại",
  KHONG_THOA_MAN_BAN_CO_MUON_TIEP_TUC_GUI_HO_SO: "không thoả mãn, Bạn có muốn tiếp tục gửi hồ sơ",
  LICH_SU_TIN_DUNG_TAI_JIVF_CUA_NGUOI_HON_PHOI: "Lịch sử tín dụng tại JIVF của người hôn phối",
  LICH_SU_TIN_DUNG_TAI_CAC_TCTD_CUA_KHACH_HANG: "Lịch sử tín dụng tại các TCTD của khách hàng",
  DIA_CHI_THUONG_TRU_GIONG_VOI_NOI_O_HIEN_TAI: "Địa chỉ thường trú giống với nơi ở hiện tại",
  VUI_LONG_NHAP_DAY_DU_CAC_THONG_TIN_BAT_BUOC: "Vui lòng nhập đầy đủ các thông tin bắt buộc",
  CAC_THONG_TIN_DA_NHAP_SE_KHONG_DUOC_LUU_LAI: "Các thông tin đã nhập sẽ không được lưu lại",
  TAT_CA_NHUNG_THONG_TIN_KIEM_TRA_HIEN_TRUONG: "1. Tất cả những thông tin kiểm tra hiện trường, xác định nhân thân, nơi ở của khách hàng được cung cấp trong báo cáo kiểm tra hiện trường là chính xác, đúng thực tế và do chính tôi thực hiện theo quy định, quy trình của Công ty.",
  VUI_LONG_TICH_CHON_LY_DO_TU_CHOI_VA_GHI_CHU: "Vui lòng tích chọn lý do từ chối và ghi chú",
  CAC_THONG_TIN_DA_NHAP_SE_KHONG_DUOC_LUU_LAI: "Các thông tin đã nhập sẽ không được lưu lại",
  VUI_LONG_NHAP_CHI_PHI_SINH_HOAT_HANG_THANG: "Vui lòng nhập chi phí sinh hoạt hàng tháng",
  VUI_LONG_CHON_DANH_GIA_CHUNG_TU_SITE_VISIT: "Vui lòng chọn đánh giá chứng từ site visit",
  KHONG_CO_HO_SO_THOA_MAN_DIEU_KIEN_TIM_KIEM: "Không có hồ sơ thỏa mãn điều kiện tìm kiếm",
  SO_TIEN_THANH_TOAN_HANG_THANG_GIAI_DOAN_1: "Số tiền thanh toán hàng tháng giai đoạn 1",
  SO_TIEN_THANH_TOAN_HANG_THANG_GIAI_DOAN_2: "Số tiền thanh toán hàng tháng giai đoạn 2",
  NGAY_CAP_KHONG_DUOC_LON_HON_NGAY_HIEN_TAI: "Ngày cấp không được lớn hơn ngày hiện tại",
  THONG_TIN_THU_THAP_TOAN_BO_NOI_DUNG_MUC_B: "Thông tin thu thập ( toàn bộ nội dung mục B)",
  BAN_MUON_THUC_HIEN_TRA_CUU_LAI_TYPE_KHONG: "Bạn muốn thực hiện tra cứu lại {{type}} không",
  LICH_SU_TIN_DUNG_TAI_JIVF_CUA_KHACH_HANG: "Lịch sử tín dụng tại JIVF của khách hàng",
  NGUOI_LIEN_HE_TRONG_TRUONG_HOP_KHAN_CAP: "Người liên hệ trong trường hợp khẩn cấp",
  NGAY_HET_HAN_PHAI_LON_HON_NGAY_HIEN_TAI: "Ngày hết hạn phải lớn hơn ngày hiện tại",
  VUI_LONG_DIEN_DAY_DU_THONG_TIN_BAT_BUOC: "Vui lòng điền đầy đủ thông tin bắt buộc",
  VUI_LONG_DIEN_DAY_DU_THONG_TIN_BAT_BUOC: "Vui lòng điền đầy đủ thông tin bắt buộc",
  DIEU_CHINH_CHI_PHI_SINH_HOAT_HANG_THANG: "Điều chỉnh chi phí sinh hoạt hàng tháng",
  VUI_LONG_NHAP_TEN_CONG_TY_NOI_LAM_VIEC: "Vui lòng nhập tên công ty/Nơi làm việc",
  NHAP_TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Nhập tổng thanh toán nợ vay hàng tháng",
  VUI_LONG_CHON_NGAY_KY_HOP_DONG_DU_KIEN: "Vui lòng chọn ngày ký hợp đồng dự kiến",
  VUI_LONG_CHON_THAM_DINH_QUA_DIEN_THOAI: "Vui lòng chọn Thẩm định qua điện thoại",
  BAN_CO_CHAC_CHAN_MUON_CAP_NHAT_LAI_CIF: "Bạn có chắc chắn muốn cập nhật lại CIF",
  NHAP_TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Nhập tổng thanh toán nợ vay hàng tháng",
  VUI_LONG_NHAP_GHI_CHU_Y_KIEN_PHE_DUYET: "Vui lòng nhập ghi chú ý kiến phê duyệt",
  NGAY_SINH_KHONG_DUOC_LON_HON_NGAY_CAP: "Ngày sinh không được lớn hơn ngày cấp",
  VUI_LONG_NHAP_DUNG_DINH_DANG_CUA_CMND: "Vui lòng nhập đúng định dạng của CMND",
  DIA_CHI_THUONG_TRU_TRUNG_VOI_DIA_CHI: "Địa chỉ thường trú trùng với địa chỉ",
  BAN_MUON_HUY_HO_SO_CONTENT_THAM_DINH: "Bạn muốn hủy hồ sơ {{content}} thẩm định",
  NHAP_GIA_TRI_TOAN_BO_TAI_SAN_DAM_BAO: "Nhập giá trị toàn bộ tài sản đảm bảo",
  VUI_LONG_NHAP_SO_DIEN_THOAI_CONG_TY: "Vui lòng nhập số điện thoại công ty",
  _DOC_DOCX_XLS_XLSX_JPG_JPEG_PNG_PDF: ".doc, .docx,.xls, .xlsx, .jpg, .jpeg, .png, .pdf.",
  GIOI_TINH_KHONG_TRUNG_KHOP_VOI_CCCD: "Giới tính không trùng khớp với CCCD",
  VUI_LONG_XEM_DIEM_XEP_HANG_TIN_DUNG: "Vui lòng xem điểm xếp hạng tín dụng",
  VUI_LONG_TICH_CHON_Y_KIEN_PHE_DUYET: "Vui lòng tích chọn ý kiến phê duyệt",
  VUI_LONG_TICH_CHON_Y_KIEN_THAM_DINH: "Vui lòng tích chọn ý kiến thẩm định",
  SO_TIEN_VAY_DUOC_PHE_DUYET_GAN_NHAT: "Số tiền vay được phê duyệt gần nhất",
  SO_KY_DA_TRA_CUA_KHOAN_VAY_GAN_NHAT: "Số kỳ đã trả của khoản vay gần nhất",
  KHONG_CO_KET_QUA_NAO_DUOC_TIM_THAY_: "Không có kết quả nào được tìm thấy ",
  VUI_LONG_NHAP_DIA_CHI_NOI_LAM_VIEC: "Vui lòng nhập địa chỉ nơi làm việc",
  CHON_NGHE_NGHIEP_CUA_THU_NHAP_KHAC: "Chọn nghề nghiệp của thu nhập khác",
  KHOAN_THANH_TOAN_NO_VAY_HANG_THANG: "Khoản thanh toán nợ vay hàng tháng",
  NAM_SINH_KHONG_TRUNG_KHOP_VOI_CCCD: "Năm sinh không trùng khớp với CCCD",
  VUI_LONG_CHON_HINH_THUC_THANH_TOAN: "Vui lòng chọn hình thức thanh toán",
  VUI_LONG_NHAP_THU_NHAP_HANG_THANG: "Vui lòng nhập thu nhập hàng tháng",
  TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Tổng thanh toán nợ vay hàng tháng",
  NHAP_CHI_PHI_SINH_HOAT_HANG_THANG: "Nhập chi phí sinh hoạt hàng tháng",
  CHUA_CO_DU_LIEU_XEP_HANG_TIN_DUNG: "Chưa có dữ liệu xếp hạng tín dụng",
  TONG_THANH_TOAN_NO_VAY_HANG_THANG: "Tổng thanh toán nợ vay hàng tháng",
  DIEU_CHINH_TONG_THANH_TOAN_NO_VAY: "Điều chỉnh tổng thanh toán nợ vay",
  VUI_LONG_NHAP_DIA_CHI_THUONG_TRU: "Vui lòng nhập địa chỉ thường trú",
  VUI_LONG_NHAP_SO_NGUOI_PHU_THUOC: "Vui lòng nhập số người phụ thuộc",
  LOI_VUI_LONG_THU_LAI_SAU_IT_PHUT: "Lỗi, vui lòng thử lại sau ít phút",
  VUI_LONG_THEM_BAO_CAO_SITE_VISIT: "Vui lòng thêm báo cáo site visit",
  THEM_BAO_CAO_SITE_VISIT_THAT_BAI: "Thêm báo cáo site visit thất bại!",
  VUI_LONG_TICH_CHON_SAN_PHAM_BAN_: "Vui lòng tích chọn sản phẩm bán ",
  BO_SUNG_THAM_DINH_QUA_DIEN_THOAI: "Bổ sung thẩm định qua điện thoại",
  DIEM_TIN_DUNG_CUA_NGUOI_HON_PHOI: "Điểm tín dụng của người hôn phối",
  VUI_LONG_NHAP_CHI_PHI_SINH_HOAT: "Vui lòng nhập chi phí sinh hoạt",
  VUI_LONG_NHAP_SO_TIEN_TRA_TRUOC: "Vui lòng nhập số tiền trả trước",
  CHON_NGAY_THANH_TOAN_HANG_THANG: "Chọn ngày thanh toán hàng tháng",
  KHACH_HANG_THUC_HIEN_THANH_TOAN: "Khách hàng thực hiện thanh toán",
  VUI_LONG_CHON_TINH_TRANG_CU_TRU: "Vui lòng chọn tình trạng cư trú",
  TEP_TAI_LEN_CHUA_DUNG_DINH_DANG: "Tệp tải lên chưa đúng định dạng",
  TAT_CA_NHUNG_HINH_ANH_THONG_TIN: "2. Tất cả những hình ảnh, thông tin là do tôi tự chụp, tự thu thập, không bị chỉnh sửa, làm giả hoặc cố tình làm sai lệch, cũng không bị tác động từ khách hàng hay cửa hàng liên kết để bỏ qua bất kỳ bước kiểm tra hoặc nghi vấn nào.",
  DIA_CHI_THUONG_TRU_TREN_CIC_PCB: "Địa chỉ thường trú trên CIC/PCB",
  GIA_TRI_TOAN_BO_TAI_SAN_DAM_BAO: "Giá trị toàn bộ tài sản đảm bảo",
  TRA_THONG_TIN_THEO_CCCD_CMND_CU: "Tra thông tin theo CCCD/CMND cũ",
  Y_KIEN_THAM_DINH_QUA_DIEN_THOAI: "Ý kiển thẩm định qua điện thoại",
  DUNG_LUONG_TOI_DA_CHO_PHEP_5MB: "Dung lượng tối đa cho phép 5MB",
  GIA_BAN_TOI_DA_LA_MAXPRICE_VND: "Giá bán tối đa là {{maxPrice}} VND",
  VUI_LONG_CHON_TRINH_DO_HOC_VAN: "Vui lòng chọn trình độ học vấn",
  TOI_THEO_DAY_CAM_KET_VA_DONG_Y: "Tôi theo đây cam kết và đồng ý rằng bất kỳ sự gian dối nào trong việc cam kết/xem xét, xác nhận các hồ sơ của khách hàng hoặc hồ sơ, hình ảnh do tôi tự chụp cũng đều là hành vi vi phạm nghiêm trọng nội quy của công ty và sẽ phải chịu kỷ luật mức cao nhất là sa thải và phải bồi thường mọi thiệt hại cho Công ty.",
  XU_LY_THAM_DINH_QUA_DIEN_THOAI: "Xử lý thẩm định qua điện thoại",
  DIEU_CHINH_THU_NHAP_HANG_THANG: "Điều chỉnh thu nhập hàng tháng",
  NHAP_TEN_CONG_TY_NOI_LAM_VIEC: "Nhập tên công ty/Nơi làm việc",
  NGHE_NGHIEP_CUA_THU_NHAP_KHAC: "Nghề nghiệp của thu nhập khác",
  VUI_LONG_NHAP_TY_LE_TRA_TRUOC: "Vui lòng nhập tỷ lệ trả trước",
  VUI_LONG_CHON_NGAY_THANH_TOAN: "Vui lòng chọn ngày thanh toán",
  TONG_SO_TIEN_VAY_MUA_BAO_HIEM: "Tổng số tiền vay mua bảo hiểm",
  TY_LE_PHI_BAO_HIEM_THEO_THANG: "Tỷ lệ phí bảo hiểm theo tháng",
  SO_TIEN_BAO_HIEM_TAM_TINH_VND: "Số tiền bảo hiểm tạm tính (VND)",
  VUI_LONG_NHAP_DIA_CHI_TAM_TRU: "Vui lòng nhập địa chỉ tạm trú",
  DIEU_CHINH_SO_NGUOI_PHU_THUOC: "Điều chỉnh số người phụ thuộc",
  VUI_LONG_NHAP_NOI_O_HIEN_TAI: "Vui lòng nhập nơi ở hiện tại",
  CHUONG_TRINH_VAY_VA_SAN_PHAM: "Chương trình vay và sản phẩm",
  THONG_TIN_KHACH_HANG_BO_SUNG: "Thông tin khách hàng bổ sung",
  VUI_LONG_CHON_TINH_THANH_PHO: "Vui lòng chọn tỉnh/ thành phố",
  VUI_LONG_NHAP_THANG_LAM_VIEC: "Vui lòng nhập tháng làm việc",
  CHI_PHI_SINH_HOAT_HANG_THANG: "Chi phí sinh hoạt hàng tháng",
  DA_CO_LOI_XAY_RA_KHI_TRA_CUU: "Đã có lỗi xảy ra khi tra cứu",
  CHUNG_TU_CUA_NGUOI_PHE_DUYET: "Chứng từ của người phê duyệt",
  DIEM_TIN_DUNG_CUA_KHACH_HANG: "Điểm tín dụng của khách hàng",
  THONG_TIN_DINH_DANH_CA_NHAN: "Thông tin định danh cá nhân",
  VUI_LONG_NHAP_THU_NHAP_KHAC: "Vui lòng nhập thu nhập khác",
  VUI_LONG_NHAP_SO_DIEN_THOAI: "Vui lòng nhập số điện thoại",
  VUI_LONG_CHON_LY_DO_TU_CHOI: "Vui lòng chọn lý do từ chối",
  VUI_LONG_CHON_LOAI_CHUNG_TU: "Vui lòng chọn loại chứng từ",
  VUI_LONG_CHON_LY_DO_TU_CHOI: "Vui lòng chọn lý do từ chối",
  VUI_LONG_NHAP_THANG_CU_TRU: "Vui lòng nhập tháng cư trú",
  NHAP_SO_DIEN_THOAI_CONG_TY: "Nhập số điện thoại công ty",
  NHAP_SO_DIEN_THOAI_DI_DONG: "Nhập số điện thoại di động",
  THONG_TIN_HOP_DONG_MUA_BAN: "Thông tin hợp đồng mua bán",
  NGAY_THANH_TOAN_HANG_THANG: "Ngày thanh toán hàng tháng",
  VUI_LONG_CHON_MUC_DICH_VAY: "Vui lòng chọn mục đích vay",
  VUI_LONG_NHAP_NAM_LAM_VIEC: "Vui lòng nhập năm làm việc",
  VUI_LONG_CHON_NHA_CUNG_CAP: "Vui lòng chọn nhà cung cấp",
  THONG_TIN_HOP_DONG_MUA_BAN: "Thông tin hợp đồng mua bán",
  XEM_DIEM_XEP_HANG_TIN_DUNG: "Xem điểm xếp hạng tín dụng",
  NHAP_DIA_CHI_NOI_LAM_VIEC: "Nhập địa chỉ nơi làm việc",
  NHAP_SO_HOP_DONG_UY_QUYEN: "Nhập Số hợp đồng ủy quyền",
  VUI_LONG_CHON_NGHE_NGHIEP: "Vui lòng chọn nghề nghiệp",
  VUI_LONG_NHAP_TEN_CONG_TY: "Vui lòng nhập tên công ty",
  THONG_TIN_NGUOI_LIEN_QUAN: "Thông tin người liên quan",
  VUI_LONG_CHON_MOI_QUAN_HE: "Vui lòng chọn mối quan hệ",
  THOI_GIAN_LAM_VIEC_DA_HET: "Thời gian làm việc đã hết",
  THONG_TIN_EKYC_KHACH_HANG: "Thông tin eKYC khách hàng",
  CHON_HINH_THUC_THANH_TOAN: "Chọn hình thức thanh toán",
  PHI_BAO_HIEM_TAM_TINH_VND: "Phí bảo hiểm tạm tính (VND)",
  TY_LE_PHAN_TRAM_TRA_TRUOC: "Tỷ lệ % trả trước",
  THONG_TIN_NGUOI_LIEN_QUAN: "Thông tin người liên quan",
  NHOM_NO_CAO_NHAT_HIEN_TAI: "Nhóm nợ cao nhất hiện tại",
  VUI_LONG_NHAP_NAM_CU_TRU: "Vui lòng nhập năm cư trú",
  TEN_CONG_TY_NOI_LAM_VIEC: "Tên công ty/Nơi làm việc",
  NHAP_THU_NHAP_HANG_THANG: "Nhập thu nhập hàng tháng",
  NHAP_SO_HOP_DONG_MUA_BAN: "Nhập Số hợp đồng mua bán",
  NGAY_KI_HOP_DONG_MUA_BAN: "Ngày kí hợp đồng mua bán",
  TEN_HANG_HOA_LABEL_TITLE: "Tên {{title}}",
  NGAY_KY_HOP_DONG_DU_KIEN: "Ngày ký hợp đồng dự kiến",
  VUI_LONG_CHON_KY_HAN_VAY: "Vui lòng chọn kỳ hạn vay",
  VUI_LONG_CHON_QUAN_HUYEN: "Vui lòng chọn quận/ huyện",
  THONG_TIN_NGUOI_HON_PHOI: "Thông tin người hôn phối",
  TAI_CHINH_NGUOI_HON_PHOI: "Tài chính người hôn phối",
  THAM_DINH_QUA_DIEN_THOAI: "Thẩm định qua điện thoại",
  DIEU_CHINH_THU_NHAP_KHAC: "Điều chỉnh thu nhập khác",
  CHUNG_TU_DINH_KEM_CUA_SC: "Chứng từ đính kèm của SC",
  THONG_TIN_NGUOI_HON_PHOI: "Thông tin người hôn phối",
  SO_NGAY_TRE_HAN_HIEN_TAI: "Số ngày trễ hạn hiện tại",
  CHON_DIA_DIEM_SITE_VISIT: "Chọn địa điểm site visit",
  KHONG_CO_HAN_MUC_DE_XUAT: "Không có hạn mức đề xuất",
  DIA_CHI_THUONG_TRU_EKYC: 'Địa chỉ thường trú ({{ekycType}})',
  NHAP_DIA_CHI_THUONG_TRU: "Nhập địa chỉ thường trú",
  DINH_DANG_FILE_CHO_PHEP: "Định dạng file cho phép",
  THEM_BAO_HIEM_TU_NGUYEN: "Thêm bảo hiểm tự nguyện",
  VUI_LONG_CHON_PHUONG_XA: "Vui lòng chọn phường / xã",
  NHAP_THOI_GIAN_LAM_VIEC: "Nhập thời gian làm việc",
  NHAP_SO_NGUOI_PHU_THUOC: "Nhập số người phụ thuộc",
  VUI_LONG_NHAP_HO_VA_TEN: "Vui lòng nhập họ và tên",
  TONG_GIA_HANG_HOA_TITLE: "Tổng giá {{title}}",
  NHAP_THONG_TIN_THU_THAP: "Nhập thông tin thu thập",
  NHAP_SO_NGUOI_PHU_THUOC: "Nhập số người phụ thuộc",
  CHON_TINH_TRANG_CU_TRU: "Chọn tình trạng cư trú",
  NHAP_CHI_PHI_SINH_HOAT: "Nhập chi phí sinh hoạt",
  NHAP_TEN_TEN_GOI_O_NHA: "Nhập tên tên gọi ở nhà",
  VUI_LONG_NHAP_SO_THANG: "Vui lòng nhập số tháng",
  HAY_CHON_LOAI_CHUNG_TU: "Hãy chọn loại chứng từ",
  NHAP_DIA_CHI_SITE_VIST: "Nhập địa chỉ site vist",
  YEU_CAU_SITE_VISIT_TAI: "Yêu cầu site visit tại",
  SO_DIEN_THOAI_CONG_TY: "Số điện thoại công ty",
  VUI_LONG_TAI_LEN_FILE: "Vui lòng tải lên file",
  VUI_LONG_KIEM_TRA_LAI: "Vui lòng kiểm tra lại",
  SO_DIEN_THOAI_DI_DONG: "Số điện thoại di động",
  CHON_CHUONG_TRINH_VAY: "Chọn chương trình vay",
  CHON_TRINH_DO_HOC_VAN: "Chọn trình độ học vấn",
  VUI_LONG_CHON_CHUC_VU: "Vui lòng chọn chức vụ",
  VUI_LONG_NHAP_SO_TIEN: "Vui lòng nhập số tiền",
  THEM_CHUNG_TU_BO_SUNG: "Thêm chứng từ bổ sung",
  CHON_TEN_GOI_BAO_HIEM: "Chọn tên gói bảo hiểm",
  VUI_LONG_CHON_CAM_KET: "Vui lòng chọn cam kết",
  VUI_LONG_NHAP_DU_LIEU: "Vui lòng nhập dữ liệu",
  CHON_CHUNG_TU_BO_SUNG: "Chọn chứng từ bổ sung",
  DIA_CHI_NOI_LAM_VIEC: "Địa chỉ nơi làm việc",
  VUI_LONG_CHON_DAI_LY: "Vui lòng chọn đại lý",
  SO_HOP_DONG_UY_QUYEN: "Số hợp đồng ủy quyền",
  CHON_NGAY_THANH_TOAN: "Chọn ngày thanh toán",
  LAI_SUAT_GIAI_DOAN_1: "Lãi suất giai đoạn 1",
  LAI_SUAT_GIAI_DOAN_2: "Lãi suất giai đoạn 2",
  TEN_THUONG_GOI_O_NHA: "Tên thường gọi ở nhà",
  VUI_LONG_NHAP_SO_NAM: "Vui lòng nhập số năm",
  CONG_VIEC_KHACH_HANG: "Công việc khách hàng",
  TAI_CHINH_KHACH_HANG: "Tài chính khách hàng",
  VUI_LONG_UPLOAD_FILE: "Vui lòng upload file",
  GIA_DINH_KET_QUA_DTI: "Giả định kết quả DTI",
  HINH_THUC_THANH_TOAN: "Hình thức thanh toán",
  NHAP_DIA_CHI_TAM_TRU: "Nhập địa chỉ tạm trú",
  GUI_HO_SO_THANH_CONG: "Gửi hồ sơ thành công",
  LUU_HO_SO_THANH_CONG: "Lưu hồ sơ thành công",
  PHE_DUYET_CHINH_THUC: "Phê duyệt chính thức",
  THONG_TIN_KHACH_HANG: "Thông tin khách hàng",
  TAI_CHINH_KHACH_HANG: "Tài chính khách hàng",
  SO_HS_DUOC_PHE_DUYET: "Số HS được phê duyệt",
  VUI_LONG_CHON_Y_KIEN: "Vui lòng chọn ý kiến",
  NHAP_YEU_CAU_BO_SUNG: "Nhập yêu cầu bổ sung",
  BO_CAU_HOI_THAM_DINH: "Bộ câu hỏi thẩm định",
  NHAP_NOI_O_HIEN_TAI: "Nhập nơi ở hiện tại",
  THU_NHAP_HANG_THANG: "Thu nhập hàng tháng",
  NGUON_THU_NHAP_KHAC: "Nguồn thu nhập khác",
  NHAP_TEN_NOI_BAN_XE: "Nhập tên nơi bán xe",
  SO_HOP_DONG_MUA_BAN: "Số hợp đồng mua bán",
  THONG_TIN_KHOAN_VAY: "Thông tin khoản vay",
  CHON_TINH_THANH_PHO: "Chọn tỉnh/ thành phố",
  TEP_TAI_LEN_QUA_LON: "Tệp tải lên quá lớn",
  SO_CMND_DA_DUOC_CAP: "Số CMND đã được cấp",
  CHUNG_TU_SITE_VISIT: "Chứng từ site visit",
  XEM_YEU_CAU_BO_SUNG: "Xem yêu cầu bổ sung",
  NHAP_THU_NHAP_THANG: "Nhập thu nhập tháng",
  DIA_DIEM_SITE_VISIT: "Địa điểm site vist",
  PHE_DUYET_THAM_DINH: "Phê duyệt thẩm định",
  HO_TEN_TREN_CIC_PCB: "Họ tên trên CIC/PCB",
  THONG_TIN_KHOAN_VAY: "Thông tin khoản vay",
  CHUNG_TU_SITE_VISIT: "Chứng từ site visit",
  TONG_DU_NO_HIEN_TAI: "Tổng dư nợ hiện tại",
  TIM_KIEM_KHACH_HANG: "Tìm kiếm khách hàng",
  TEP_TAI_LEN_QUA_LON: "Tệp tải lên quá lớn",
  DIA_CHI_THUONG_TRU: 'Địa chỉ thường trú',
  NHAP_THU_NHAP_KHAC: "Nhập thu nhập khác",
  THONG_TIN_HANG_HOA: "Thông tin hàng hóa",
  KY_HAN_GIAI_DOAN_1: "Kỳ hạn giai đoạn 1",
  KY_HAN_GIAI_DOAN_2: "Kỳ hạn giai đoạn 2",
  THOI_GIAN_LAM_VIEC: "Thời gian làm việc",
  SO_NGUOI_PHU_THUOC: "Số người phụ thuộc",
  NHAP_SO_DIEN_THOAI: "Nhập số điện thoại",
  BAO_HIEM_TU_NGUYEN: "Bảo hiểm tự nguyện",
  CHON_LY_DO_TU_CHOI: "Chọn lý do từ chối",
  CHON_LOAI_CHUNG_TU: "Chọn loại chứng từ",
  XAC_NHAN_GUI_HO_SO: "Xác nhận gửi hồ sơ",
  BAO_CAO_SITE_VISIT: "Báo cáo site visit",
  DIA_CHI_SITE_VISIT: "địa chỉ site visit",
  THONG_TIN_THU_THAP: "thông tin thu thập",
  DTI_THE_DIEU_CHINH: "DTI thẻ điều chỉnh",
  BAN_MUON_GUI_HO_SO: "Bạn muốn gửi hồ sơ",
  TIEP_TUC_THAM_DINH: "Tiếp tục thẩm định",
  SO_NGUOI_PHU_THUOC: "Số người phụ thuộc",
  NHAP_THU_NHAP_KHAC: "Nhập thu nhập khác",
  CHUNG_TU_THAM_DINH: "Chứng từ thẩm định",
  TRE_HAN_THANH_TOAN: "Trễ hạn thanh toán",
  CHON_LY_DO_TU_CHOI: "Chọn lý do từ chối",
  TINH_TRANG_CU_TRU: "Tình trạng cư trú",
  CHI_PHI_SINH_HOAT: "Chi phí sinh hoạt",
  CHON_NGAY_HET_HAN: "Chọn ngày hết hạn",
  CHON_NOI_CAP_CCCD: "Chọn nơi cấp CCCD",
  NHOM_SAN_PHAM_VAY: "Nhóm sản phẩm vay",
  NHAP_GIA_CHUA_VAT: "Nhập giá chưa VAT",
  NHAP_SO_TAI_KHOAN: "Nhập số tài khoản",
  CHON_NHA_SAN_XUAT: "Chọn nhà sản xuất",
  CHON_TEN_HANG_HOA: "Chọn Tên hàng hoá",
  TONG_GIA_HANG_HOA: "Tổng giá hàng hóa",
  DON_GIA_CUA_TITLE: "Đơn giá (của {{title}})",
  SO_TIEN_TRA_TRUOC: "Số tiền trả trước",
  CHON_MUC_DICH_VAY: "Chọn mục đích vay",
  CHON_CHON_CHUC_VU: "Chọn chọn chức vụ",
  DE_XUAT_KHOAN_VAY: "Đề xuất khoản vay",
  CHUNG_TU_DINH_KEM: "Chứng từ đính kèm",
  DIEM_DTI_HIEN_TAI: "Điểm DTI hiện tại",
  CHON_NHA_CUNG_CAP: "Chọn nhà cung cấp",
  HUY_BO_SUNG_HO_SO: "Hủy bổ sung hồ sơ",
  XEM_HO_SO_BAN_DAU: "Xem hồ sơ ban đầu",
  BO_SUNG_THAM_DINH: "Bổ sung thẩm định",
  XEP_HANG_TIN_DUNG: "Xếp hạng tín dụng",
  THOI_GIAN_CU_TRU: "Thời gian cư trú",
  CHON_NGHE_NGHIEP: "Chọn nghề nghiệp",
  THOI_GIAN_UPLOAD: "Thời gian upload",
  SO_CCCD_GAN_CHIP: "Số CCCD gắn chip",
  CHUONG_TRINH_VAY: "Chương trình vay",
  NHAP_GIA_SAU_VAT: "Nhập giá sau VAT",
  NHAP_SO_CHO_NGOI: "Nhập số chỗ ngồi",
  TRINH_DO_HOC_VAN: "Trình độ học vấn",
  THUONG_TRU_MA_QR: "thường trú ( Mã QR )",
  NHAP_TEN_CONG_TY: "Nhập tên công ty",
  CHON_MOI_QUAN_HE: "Chọn mối quan hệ",
  CHUNG_TU_BO_SUNG: "Chứng từ bổ sung",
  TEN_GOI_BAO_HIEM: "Tên gói bảo hiểm",
  DA_CO_LOI_XAY_RA: "Đã có lỗi xảy ra",
  TIEP_TUC_BO_SUNG: "Tiếp tục bổ sung",
  DA_CO_LOI_XAY_RA: "Đã có lỗi xảy ra",
  NGHE_NGHIEP_KHAC: "Nghề nghiệp khác",
  Y_KIEN_THAM_DINH: "Ý kiến thẩm định",
  Y_KIEN_PHE_DUYET: "Ý kiến phê duyệt",
  GIA_TRI_TRUY_VAN: "Giá trị truy vấn",
  SO_HS_BI_TU_CHOI: "Số HS bị từ chối",
  TONG_SO_TIEN_VAY: "Tổng số tiền vay",
  CHUNG_TU_BO_SUNG: "Chứng từ bổ sung",
  CHON_TINH_THANH: "Chọn tỉnh / thành",
  CHON_QUAN_HUYEN: "Chọn quận / huyện",
  TY_LE_TRA_TRUOC: "Tỷ lệ trả trước",
  NGAY_CUOI_THANG: "Ngày cuối tháng",
  SO_TIEN_VAY_GOC: "Số tiền vay gốc",
  CHON_KY_HAN_VAY: "Chọn kỳ hạn vay",
  NGUOI_PHU_THUOC: "Người phụ thuộc",
  KET_QUA_DTI_MOI: "Kết quả DTI mới",
  CHU_KY_BAO_HIEM: "Chu kỳ bảo hiểm",
  NHAP_SO_CMND_CU: "Nhập số CMND cũ",
  HO_SO_CHO_XU_LY: "Hồ sơ chờ xử lý",
  YEU_CAU_BO_SUNG: "Yêu cầu bổ sung",
  NHAP_BIEN_SO_XE: "Nhập biển số xe",
  XU_LY_THAM_DINH: "Xử lý thẩm định",
  BAO_CAO_CIC_R11: "Báo cáo CIC R11",
  BAO_CAO_CIC_R14: "Báo cáo CIC R14",
  BAO_CAO_CIC_R21: "Báo cáo CIC R21",
  BAO_CAO_CIC_S10: "Báo cáo CIC S10",
  TINH_THANH_PHO: "Tỉnh / Thành phố",
  CHON_PHUONG_XA: "Chọn phường / xã",
  NOI_O_HIEN_TAI: "Nơi ở hiện tại",
  NHAP_HO_VA_TEN: "Nhập họ và tên",
  CHON_GIOI_TINH: "Chọn giới tính",
  CHON_NGAY_SINH: "Chọn ngày sinh",
  TEN_NOI_BAN_XE: "Tên nơi bán xe",
  CHON_NGAN_HANG: "Chọn ngân hàng",
  CHON_CHI_NHANH: "Chọn chi nhánh",
  TONG_KHOAN_VAY: "Tổng khoản vay",
  KHOI_TAO_HO_SO: "Khởi tạo hồ sơ",
  THU_NHAP_THANG: "Thu nhập tháng",
  DTI_DIEU_CHINH: "DTI điều chỉnh",
  KHONG_XAC_DINH: "Không xác định",
  GHI_CHU_CUA_SC: "Ghi chú của SC",
  MO_TA_XEP_HANG: "Mô tả xếp hạng",
  CCCD_CMND_CU_1: "CCCD/CMND cũ 1",
  CCCD_CMND_CU_2: "CCCD/CMND cũ 2",
  TEN_KHACH_HANG: "Tên khách hàng",
  SAN_PHAM_CHINH: "Sản phẩm chính",
  NGUOI_YEU_CAU: "Người yêu cầu",
  NGAY_KHOI_TAO: "Ngày khởi tạo",
  THU_NHAP_KHAC: "Thu nhập khác",
  LOAI_CHUNG_TU: "Loại chứng từ",
  CHON_NGAY_CAP: "Chọn ngày cấp",
  TAI_NGAN_HANG: "Tại ngân hàng",
  NHAP_SO_LUONG: "Nhập số lượng",
  NHAP_SO_THANG: "Nhập số tháng",
  SO_DIEN_THOAI: "Số điện thoại",
  NHOM_CHUNG_TU: "Nhóm chứng từ",
  TIEP_TUC_NHAP: "Tiếp tục nhập",
  XEM_QUY_TRINH: "Xem quy trình",
  BO_SUNG_HO_SO: "Bổ sung hồ sơ",
  LOAI_BAO_HIEM: "Loại bảo hiểm",
  THU_NHAP_KHAC: "Thu nhập khác",
  DIEM_TIN_DUNG: "Điểm tín dụng",
  GUI_PHE_DUYET: "Gửi phê duyệt",
  CHON_CHUC_VU: "Chọn chức vụ",
  CHUNG_TU_LOI: "Chứng từ lỗi",
  TEP_DINH_KEM: "Tệp đính kèm",
  NGUOI_UPLOAD: "Người upload",
  NOI_CAP_CCCD: "Nơi cấp CCCD",
  SAN_PHAM_VAY: "Sản phẩm vay",
  GIA_CHUA_VAT: "Giá chưa VAT",
  SO_TAI_KHOAN: "Số tài khoản",
  NHA_SAN_XUAT: "Nhà sản xuất",
  TEN_HANG_HOA: "Tên hàng hoá",
  NAM_SAN_XUAT: "Năm sản xuất",
  NHAP_MAU_SAC: "Nhập màu sắc",
  MUC_DICH_VAY: "Mục đích vay",
  KHOAN_VAY_CU: "khoản vay cũ",
  NHAP_SO_TIEN: "Nhập số tiền",
  THEM_GHI_CHU: "Thêm ghi chú",
  DIEM_DTI_MOI: "Điểm DTI mới",
  NHA_CUNG_CAP: "Nhà cung cấp",
  NGAY_HET_HAN: "Ngày hết hạn",
  THEM_BAO_CAO: "Thêm báo cáo",
  NHAP_DIA_CHI: "Nhập địa chỉ",
  TEN_CHUNG_TU: "Tên chứng từ",
  KHONG_HOP_LE: "Không hợp lệ",
  NOI_DUNG_S37: "Nội dung S37",
  SO_CCCD_CMND: "Số CCCD/CMND",
  THEM_GHI_CHU: "Thêm ghi chú",
  NGUOI_XU_LY: "Người xử lý",
  NGHE_NGHIEP: "Nghề nghiệp",
  NO_VAY_KHAC: "Nợ vay khác",
  CHON_DAI_LY: "Chọn đại lý",
  GIA_SAU_VAT: "Giá sau VAT",
  SO_CHO_NGOI: "Số chỗ ngồi",
  KET_QUA_DTI: "Kết quả DTI",
  MOI_QUAN_HE: "Mối quan hệ",
  NHAP_KY_HAN: "Nhập kỳ hạn",
  XEM_BAO_CAO: "Xem báo cáo",
  TOI_CAM_KET: "Tôi cam kết",
  NO_VAY_KHAC: "Nợ vay khác",
  BAO_CAO_PCB: "Báo cáo PCB",
  BAO_CAO_S11: "Báo cáo S11",
  DTI_BAN_DAU: "DTI ban đầu",
  TRANG_THAI: "Trạng thái",
  QUAN_HUYEN: "Quận / Huyện",
  KY_HAN_VAY: "Kỳ hạn vay",
  TRONG_CHIP: "trong chip",
  BIEN_SO_XE: "Biển số xe",
  KY_HAN_VAY: "Kỳ hạn vay",
  PHUONG_XA: "Phường xã",
  CHI_NHANH: "Chi nhánh",
  HUY_HO_SO: "Hủy hồ sơ",
  CONG_VIEC: "Công việc",
  THONG_BAO: "Thông báo",
  HO_VA_TEN: "Họ và tên",
  GIOI_TINH: "Giới tính",
  NGAY_SINH: "Ngày sinh",
  QUOC_TICH: "Quốc tịch",
  NO_REPORT: "No Report",
  PHE_DUYET: "phê duyệt",
  THAM_DINH: "thẩm định",
  NGAY_CHAM: "Ngày chấm",
  NHAP_VAT: "Nhập VAT",
  SO_LUONG: "Số lượng",
  BAO_HIEM: "Bảo hiểm",
  DIEM_DTI: "Điểm DTI",
  XAC_NHAN: "Xác nhận",
  HANG_HOA: "Hàng hoá",
  QUAY_LAI: "Quay lại",
  QUE_QUAN: "Quê quán",
  NGAY_CAP: "Ngày cấp",
  DTI_THUC: "DTI thực",
  XEP_HANG: "Xếp hạng",
  CHUC_VU: "Chức vụ",
  DIA_CHI: "Địa chỉ",
  MAU_SAC: "Màu sắc",
  GHI_CHU: "Ghi chú",
  AP_DUNG: "Áp dụng",
  SO_CCCD: "Số CCCD",
  BO_SUNG: "bổ sung",
  CIC_S37: "CIC S37",
  CIC_R11: "CIC R11",
  TRE_HAN: "Trễ hạn",
  KET_QUA: "Kết quả",
  DAI_LY: "Đại lý",
  KY_HAN: "Kỳ hạn",
  UPLOAD: "Upload",
  HO_TEN: "Họ tên",
  HOP_LE: "Hợp lệ",
  MA_PCB: "Mã PCB",
  MA_CIC: "Mã CIC",
  ACTION: "Action",
  THANG: "Tháng",
  THOAT: "Thoát",
  XU_LY: "xử lý",
  THOAT: "Thoát",
  KHAC: "Khác",
  EKYC: "eKYC",
  DONG: "Đóng",
  CCCD: "CCCD",
  NAM: "Năm",
  VAT: "VAT",
  BAN: "bán",
  LUU: "Lưu",
  GUI: "Gửi",
  XOA: "Xóa",
  KYC: "KYC",
  CIC: "CIC",
  DTI: "DTI",
  STT: "STT",
  CIF: "CIF",
  SDT: "SĐT",
};
